// Chemistry course data — Week-based structure.
// This is the ONLY file to touch when adding lessons to this course.
// Shape: modules (weeks) -> lessons (topics) -> content blocks (+ a quiz per lesson).
//
// QUESTION TYPES — every quiz item, and every mid-lesson "check" block,
// can use one of four answer formats by setting `type` (quiz items) or
// `qtype` (check blocks — `type` is already used there to mark it as a
// checkpoint). Leaving it out defaults to "mcq".
//
//   mcq (default)  { q, options, correct, explain? }              — tap one option
//   truefalse      { q, correct: true|false, explain? }           — tap True/False
//   multi          { q, options, correct: [i, j], explain? }      — select ALL that apply
//   type           { q, accepted: ["answer", "alt answer"], explain? } — type the answer
//
// See README.md at the project root for the full block-type reference.

export const chemistry = {
  id: "chemistry-fundamentals",
  title: "Chemistry Fundamentals",
  tagline: "From atoms and ions to reactions, bonding, and nuclear chemistry.",
  icon: "flask",
  accent: "#D14F2E",
  ink: "#1A1A2E",
  modules: [
    {
      id: "m1",
      number: 1,
      section: "Week 1",
      title: "Ions, Valency, and Ionic Bonding",
      description: "Define ions, model cation/anion formation, use valency and the periodic table, and write ionic formulas including polyatomic ions.",
      lessons: [
        {
          id: "1.1",
          title: "Atoms and Ions",
          blocks: [
            { type: "p", text: "Everything in chemistry starts with atoms. An atom is the smallest unit of an element that still has that element's properties. Most of the time, atoms are neutral — they have the same number of protons (positive) and electrons (negative). But atoms can gain or lose electrons, and when they do, they become **ions**." },
            { type: "term", term: "Ion", definition: "An atom or group of atoms that has an overall electric charge because it has gained or lost electrons." },
            { type: "h", text: "Cations and anions" },
            { type: "list", items: [
              "**Cations** are positively charged ions. They form when an atom **loses** one or more electrons from its outer (valence) shell. Metals commonly form cations.",
              "**Anions** are negatively charged ions. They form when an atom **gains** one or more electrons to complete its valence shell. Non-metals commonly form anions.",
            ]},
            { type: "p", text: "For example, sodium (Na) has 11 protons and 11 electrons when neutral. If it loses one electron, it becomes Na⁺ — a cation with 11 protons and only 10 electrons. Chlorine (Cl), on the other hand, has 17 protons and 17 electrons when neutral. If it gains one electron, it becomes Cl⁻ — an anion with 17 protons and 18 electrons." },
            { type: "check", qtype: "truefalse", q: "An anion is formed when an atom loses electrons.", correct: false, explain: "Anions are formed when atoms GAIN electrons. Losing electrons forms cations." },
            { type: "callout", text: "Key rule: **lose electrons → positive cation; gain electrons → negative anion.** The charge tells you which way the electron balance has shifted." },
          ],
          quiz: [
            { q: "What is an ion?", options: ["A neutral atom", "An atom with a charge due to gaining or losing electrons", "A molecule made of two atoms", "A type of chemical bond"], correct: 1 },
            { q: "Which statement best describes a cation?", options: ["A negatively charged ion formed by gaining electrons", "A positively charged ion formed by losing electrons", "A neutral atom", "A type of covalent bond"], correct: 1 },
            { q: "What happens when a chlorine atom gains one electron?", options: ["It becomes a cation", "It becomes an anion", "It becomes neutral", "It becomes a molecule"], correct: 1 },
            { type: "type", q: "Fill in the blank: An atom that loses electrons becomes a ______.", accepted: ["cation", "positive ion", "positively charged ion"], explain: "Losing electrons leaves more protons than electrons, creating a positive cation." },
          ],
        },
        {
          id: "1.2",
          title: "Valency and the Periodic Table",
          blocks: [
            { type: "p", text: "Atoms don't gain or lose electrons randomly. They do it to achieve a **stable electron configuration** — usually a full outer (valence) shell, like the noble gases. **Valency** describes how many electrons an atom needs to gain, lose, or share to reach that stable state." },
            { type: "term", term: "Valency", definition: "The number of electrons an atom needs to gain, lose, or share to achieve a stable, full outer electron shell." },
            { type: "h", text: "Using the periodic table" },
            { type: "p", text: "The group (column) number in the periodic table tells you how many valence electrons an element has, which in turn tells you its typical valency:" },
            { type: "list", items: [
              "**Group 1** — 1 valence electron → loses 1 → forms 1+ ions (e.g. Na⁺).",
              "**Group 2** — 2 valence electrons → loses 2 → forms 2+ ions (e.g. Mg²⁺).",
              "**Group 3** — 3 valence electrons → loses 3 → forms 3+ ions (e.g. Al³⁺).",
              "**Group 15** — 5 valence electrons → gains 3 → forms 3− ions (e.g. N³⁻).",
              "**Group 16** — 6 valence electrons → gains 2 → forms 2− ions (e.g. O²⁻).",
              "**Group 17** — 7 valence electrons → gains 1 → forms 1− ions (e.g. Cl⁻).",
            ]},
            { type: "p", text: "Atoms with 1–3 valence electrons tend to **lose** them to empty their outer shell. Atoms with 5–7 valence electrons tend to **gain** electrons to fill their outer shell to 8 (the octet rule). Group 18 (noble gases) already have full outer shells, so they're mostly unreactive." },
            { type: "check", q: "An element in Group 16 has how many valence electrons, and what charge does it typically form?", options: ["6 valence electrons, 2− ion", "6 valence electrons, 2+ ion", "16 valence electrons, 6− ion", "2 valence electrons, 6+ ion"], correct: 0, explain: "Group 16 elements have 6 valence electrons and typically gain 2 to form 2− anions (e.g. O²⁻)." },
            { type: "callout", text: "Exam shortcut: **Group number → valence electrons → how many to gain/lose → ion charge.** Noble gases (Group 18) are the stable reference point." },
          ],
          quiz: [
            { q: "What does valency describe?", options: ["The number of protons in an atom", "The number of electrons an atom needs to gain, lose, or share for a full outer shell", "The total number of electrons in an atom", "The atomic mass of an element"], correct: 1 },
            { q: "How many valence electrons does a Group 2 element have?", options: ["1", "2", "3", "8"], correct: 1 },
            { q: "Which group typically forms 1− ions?", options: ["Group 1", "Group 2", "Group 16", "Group 17"], correct: 3 },
            { type: "truefalse", q: "Noble gases are mostly unreactive because they already have full valence shells.", correct: true, explain: "Noble gases (Group 18) have complete outer shells, so they don't need to gain or lose electrons." },
          ],
        },
        {
          id: "1.3",
          title: "Ionic Bonding and Simple Formulas",
          blocks: [
            { type: "p", text: "An **ionic bond** is the electrostatic attraction between oppositely charged ions — typically a metal cation and a non-metal anion. The metal loses electrons to become positive; the non-metal gains those electrons to become negative. The resulting compound is electrically neutral overall." },
            { type: "term", term: "Ionic bond", definition: "The electrostatic attraction between oppositely charged ions, usually formed between a metal and a non-metal through electron transfer." },
            { type: "h", text: "Writing ionic formulas" },
            { type: "p", text: "To write a correct ionic formula, you balance the total positive and negative charges so the compound is neutral:" },
            { type: "list", items: [
              "Write the cation (metal) first, then the anion (non-metal).",
              "Use subscripts to show how many of each ion are needed to balance the charges.",
              "Omit the charge symbols in the final formula — only the ratio matters.",
            ]},
            { type: "p", text: "Example: Sodium chloride. Na⁺ and Cl⁻ have charges of +1 and −1. One of each balances perfectly → NaCl. Magnesium oxide: Mg²⁺ and O²⁻ also balance 1:1 → MgO. But magnesium chloride is different: Mg²⁺ and Cl⁻ need two chlorides to balance one magnesium → MgCl₂." },
            { type: "check", qtype: "truefalse", q: "In an ionic compound formula, the total positive charge must equal the total negative charge.", correct: true, explain: "Exactly — ionic compounds are electrically neutral overall, so charges must balance." },
            { type: "h", text: "Transition metals" },
            { type: "p", text: "Many transition metals can form more than one possible ion (e.g. Fe²⁺ and Fe³⁺). In formulas, the charge is often shown with Roman numerals in the name — iron(II) chloride is FeCl₂, while iron(III) chloride is FeCl₃." },
            { type: "callout", text: "Formula rule of thumb: **balance the charges, then write the simplest whole-number ratio.** For transition metals, pay attention to the stated charge (e.g. copper(II) = Cu²⁺)." },
          ],
          quiz: [
            { q: "What type of bond forms between a metal and a non-metal through electron transfer?", options: ["Covalent bond", "Ionic bond", "Metallic bond", "Hydrogen bond"], correct: 1 },
            { q: "What is the correct formula for magnesium chloride?", options: ["MgCl", "MgCl₂", "Mg₂Cl", "Mg₂Cl₂"], correct: 1 },
            { q: "In iron(III) chloride, what is the charge on the iron ion?", options: ["1+", "2+", "3+", "4+"], correct: 2 },
            { type: "type", q: "Write the formula for sodium oxide (Na⁺ and O²⁻).", accepted: ["Na2O", "Na₂O"], explain: "Two Na⁺ ions (+1 each) are needed to balance one O²⁻ ion (−2), giving Na₂O." },
          ],
        },
        {
          id: "1.4",
          title: "Polyatomic Ions and Complex Formulas",
          blocks: [
            { type: "p", text: "Not all ions are single atoms. Some are groups of atoms bonded together that carry an overall charge — these are **polyatomic ions**. They behave just like simple ions when forming compounds, but you must treat the whole group as a single unit." },
            { type: "term", term: "Polyatomic ion", definition: "A group of atoms bonded together that has an overall electric charge and acts as a single ion in compounds." },
            { type: "h", text: "Common polyatomic ions" },
            { type: "list", items: [
              "**Sulfate**: SO₄²⁻",
              "**Carbonate**: CO₃²⁻",
              "**Nitrate**: NO₃⁻",
              "**Hydroxide**: OH⁻",
              "**Ammonium**: NH₄⁺",
              "**Phosphate**: PO₄³⁻",
            ]},
            { type: "p", text: "When writing formulas with polyatomic ions, the same charge-balancing rules apply — but if you need more than one polyatomic ion, you must put the entire ion formula in **parentheses** and add the subscript outside." },
            { type: "p", text: "Example: Calcium nitrate. Ca²⁺ and NO₃⁻. You need two nitrates to balance one calcium → Ca(NO₃)₂. The parentheses show that the subscript 2 applies to the whole NO₃ group, not just the oxygen." },
            { type: "check", q: "Which formula correctly represents ammonium sulfate (NH₄⁺ and SO₄²⁻)?", options: ["NH₄SO₄", "(NH₄)₂SO₄", "NH₄(SO₄)₂", "(NH₄)₂(SO₄)₂"], correct: 1, explain: "Two NH₄⁺ ions (+1 each) balance one SO₄²⁻ ion (−2), giving (NH₄)₂SO₄." },
            { type: "callout", text: "Memory aid: **If you need more than one polyatomic ion, wrap it in brackets and put the number outside.** This avoids ambiguity about what the subscript applies to." },
          ],
          quiz: [
            { q: "What is the formula for the carbonate ion?", options: ["CO₃²⁻", "CO₄²⁻", "C₂O₃²⁻", "CO₂²⁻"], correct: 0 },
            { q: "What is the correct formula for magnesium nitrate (Mg²⁺ and NO₃⁻)?", options: ["MgNO₃", "Mg(NO₃)₂", "Mg₂NO₃", "Mg₂(NO₃)₂"], correct: 1 },
            { q: "Which of these is a polyatomic cation?", options: ["Na⁺", "NH₄⁺", "Cl⁻", "Ca²⁺"], correct: 1 },
            { type: "truefalse", q: "When writing formulas with polyatomic ions, you never need to use parentheses.", correct: false, explain: "You MUST use parentheses when more than one polyatomic ion is needed (e.g. Ca(NO₃)₂)." },
          ],
        },
      ],
    },
    {
      id: "m2",
      number: 2,
      section: "Week 2",
      title: "Covalent Bonding, Lewis Diagrams, Acids & Bases",
      description: "Describe covalent bonds, write formulas, recognise diatomic molecules, draw Lewis dot diagrams, and define acids, bases, and pH.",
      lessons: [
        {
          id: "2.1",
          title: "Covalent Bonding",
          blocks: [
            { type: "p", text: "Not all bonds involve electron transfer. When two **non-metal** atoms bond, they typically **share** electrons instead — this is a **covalent bond**. Each shared pair of electrons counts toward the full outer shell of both atoms." },
            { type: "term", term: "Covalent bond", definition: "A chemical bond formed when two non-metal atoms share one or more pairs of valence electrons to achieve full outer shells." },
            { type: "h", text: "Simple covalent formulas" },
            { type: "p", text: "Covalent compounds are written by showing how many atoms of each element are in the molecule. For example, water is H₂O (two hydrogens, one oxygen), carbon dioxide is CO₂, and methane is CH₄. Unlike ionic compounds, there are no charges to balance — the formulas reflect how atoms share electrons to complete their shells." },
            { type: "check", qtype: "truefalse", q: "Covalent bonds typically form between a metal and a non-metal.", correct: false, explain: "Covalent bonds form between NON-METAL atoms. Metal + non-metal usually forms ionic bonds." },
            { type: "callout", text: "Key contrast: **ionic = electron transfer (metal + non-metal); covalent = electron sharing (non-metal + non-metal).**" },
          ],
          quiz: [
            { q: "What type of bond forms when two non-metals share electrons?", options: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"], correct: 1 },
            { q: "Which of these is a covalent compound?", options: ["NaCl", "MgO", "H₂O", "CaCl₂"], correct: 2 },
            { q: "In covalent bonding, electrons are:", options: ["Transferred from metal to non-metal", "Shared between non-metal atoms", "Lost from the atom entirely", "Stored in the nucleus"], correct: 1 },
            { type: "truefalse", q: "Methane (CH₄) is an example of a covalent compound.", correct: true, explain: "CH₄ consists of carbon and hydrogen (both non-metals) sharing electrons." },
          ],
        },
        {
          id: "2.2",
          title: "Diatomic Molecules",
          blocks: [
            { type: "p", text: "Some elements naturally exist as **diatomic molecules** — two atoms of the same element bonded together. This is their stable form under normal conditions." },
            { type: "h", text: "The seven common diatomic elements" },
            { type: "list", items: [
              "**Hydrogen**: H₂",
              "**Nitrogen**: N₂",
              "**Fluorine**: F₂",
              "**Oxygen**: O₂",
              "**Iodine**: I₂",
              "**Chlorine**: Cl₂",
              "**Bromine**: Br₂",
            ]},
            { type: "p", text: "A common mnemonic is 'Have No Fear Of Ice Cold Beer' (H, N, F, O, I, Cl, Br). These elements are more stable as pairs than as single atoms because sharing electrons gives each atom a full outer shell." },
            { type: "check", q: "Which of these is a diatomic molecule?", options: ["He", "Ne", "O₂", "Ar"], correct: 2, explain: "Oxygen exists as O₂; helium, neon, and argon are noble gases and exist as single atoms." },
            { type: "callout", text: "Memory trick: **Have No Fear Of Ice Cold Beer → H, N, F, O, I, Cl, Br.**" },
          ],
          quiz: [
            { q: "Which element exists as a diatomic molecule?", options: ["Helium", "Nitrogen", "Neon", "Argon"], correct: 1 },
            { q: "What is the formula for chlorine gas?", options: ["Cl", "Cl₂", "Cl₃", "2Cl"], correct: 1 },
            { q: "Why do some elements form diatomic molecules?", options: ["To become ions", "To achieve a full outer shell by sharing electrons", "To increase their mass", "To become metals"], correct: 1 },
            { type: "multi", q: "Select all the diatomic elements.", options: ["Hydrogen (H₂)", "Oxygen (O₂)", "Carbon (C)", "Fluorine (F₂)"], correct: [0, 1, 3], explain: "H₂, O₂, and F₂ are diatomic; carbon is not typically diatomic under normal conditions." },
          ],
        },
        {
          id: "2.3",
          title: "Lewis Electron Dot Diagrams",
          blocks: [
            { type: "p", text: "Lewis diagrams show only the **valence electrons** of an atom or molecule. The element symbol represents the nucleus and inner electrons; dots (or crosses) around it represent valence electrons. Shared pairs are shown either as two dots between atoms or as a dash (—)." },
            { type: "h", text: "Drawing Lewis diagrams" },
            { type: "list", items: [
              "Draw the element symbol.",
              "Add dots around it to represent valence electrons (up to 8, in pairs).",
              "For molecules, show shared pairs between atoms as bonding pairs.",
              "Unshared pairs (lone pairs) remain on individual atoms.",
            ]},
            { type: "p", text: "Example: H₂. Each hydrogen has 1 valence electron. They share their electrons to form a single covalent bond: H—H or H:H. Each H now effectively has 2 electrons (a full shell for hydrogen)." },
            { type: "check", qtype: "truefalse", q: "In a Lewis diagram, only valence electrons are shown.", correct: true, explain: "Lewis diagrams show ONLY the outer-shell (valence) electrons, not inner electrons." },
            { type: "callout", text: "Lewis diagrams make electron sharing visible: **dots = valence electrons; lines or paired dots = shared (bonding) pairs.**" },
          ],
          quiz: [
            { q: "In a Lewis diagram, what do the dots represent?", options: ["Protons", "Neutrons", "All electrons", "Valence electrons only"], correct: 3 },
            { q: "How many valence electrons does oxygen have in a Lewis diagram?", options: ["2", "4", "6", "8"], correct: 2 },
            { q: "What does a line (dash) between two atoms represent in a Lewis diagram?", options: ["A lone pair", "A shared pair of electrons (a bond)", "A proton", "A neutron"], correct: 1 },
            { type: "truefalse", q: "A Lewis diagram for nitrogen (Group 15) would show 5 valence electrons.", correct: true, explain: "Group 15 elements have 5 valence electrons, shown as 5 dots around the symbol." },
          ],
        },
        {
          id: "2.4",
          title: "Lewis Diagrams for Ionic and Covalent Compounds",
          blocks: [
            { type: "p", text: "Lewis diagrams can show both ionic and covalent bonding, but they look different for each type." },
            { type: "h", text: "Ionic compounds" },
            { type: "list", items: [
              "Show the metal atom losing electrons (arrows from metal to non-metal).",
              "Draw the resulting ions in brackets with their charges.",
              "Example: Na· + ·Cl: → [Na]⁺ + [:Cl:]⁻.",
            ]},
            { type: "h", text: "Covalent compounds" },
            { type: "list", items: [
              "Show atoms sharing electrons so each achieves a full valence shell.",
              "Shared pairs are drawn between atoms; lone pairs stay on individual atoms.",
              "Example: H· + ·H → H:H (or H—H).",
            ]},
            { type: "check", q: "In a Lewis diagram for an ionic compound, how are ions typically shown?", options: ["Without charges", "In brackets with charges written", "As shared electrons only", "As a single combined symbol"], correct: 1, explain: "Ionic Lewis diagrams show ions in brackets with their charges, e.g. [Na]⁺ and [:Cl:]⁻." },
            { type: "callout", text: "Visual difference: **ionic = electron transfer + charged ions; covalent = shared pairs between atoms.**" },
          ],
          quiz: [
            { q: "In Lewis diagrams, ionic bonding is shown as:", options: ["Shared electrons only", "Transfer of electrons with charged ions", "No electrons shown", "Only lone pairs"], correct: 1 },
            { q: "In Lewis diagrams, covalent bonding is shown as:", options: ["Transfer of electrons", "Shared pairs of electrons", "Charged ions only", "No bonds shown"], correct: 1 },
            { q: "Which would you see in a Lewis diagram of NaCl?", options: ["Shared electrons between Na and Cl", "Na⁺ and Cl⁻ ions with charges", "Only neutral atoms", "No electrons at all"], correct: 1 },
            { type: "truefalse", q: "A Lewis diagram for H₂O would show oxygen sharing electrons with two hydrogen atoms.", correct: true, explain: "Oxygen shares one pair with each hydrogen, giving O two bonds and two lone pairs." },
          ],
        },
        {
          id: "2.5",
          title: "Acids, Bases, and the pH Scale",
          blocks: [
            { type: "p", text: "Acids and bases are two important classes of compounds that behave oppositely in water. The **pH scale** measures how acidic or basic a solution is, running from about 0 to 14." },
            { type: "term", term: "pH scale", definition: "A scale from 0 to 14 that measures the acidity or basicity of a solution. pH < 7 is acidic, pH = 7 is neutral, pH > 7 is basic." },
            { type: "h", text: "Definitions" },
            { type: "list", items: [
              "**Acid**: A substance that releases hydrogen ions (H⁺) when dissolved in water. Acids have pH < 7.",
              "**Base**: A substance that releases hydroxide ions (OH⁻) when dissolved in water. Bases have pH > 7.",
              "**Neutral**: pH = 7, where [H⁺] = [OH⁻], like pure water.",
            ]},
            { type: "p", text: "Examples: Vinegar (acetic acid) is acidic and used in cooking and cleaning. Antacids (like magnesium hydroxide) are basic and used to neutralise excess stomach acid." },
            { type: "check", q: "Which statement is true about acids?", options: ["They release OH⁻ ions in water", "They release H⁺ ions in water", "They always have pH > 7", "They are always solids"], correct: 1, explain: "Acids release H⁺ ions in water and have pH < 7." },
            { type: "h", text: "The pH scale in practice" },
            { type: "list", items: [
              "pH 0–3: Strong acids (e.g. stomach acid, battery acid).",
              "pH 4–6: Weak acids (e.g. vinegar, lemon juice).",
              "pH 7: Neutral (pure water).",
              "pH 8–10: Weak bases (e.g. baking soda, soap).",
              "pH 11–14: Strong bases (e.g. bleach, drain cleaner).",
            ]},
            { type: "callout", text: "Simple rule: **more H⁺ → lower pH → more acidic; more OH⁻ → higher pH → more basic.** Neutral is the middle point at pH 7." },
          ],
          quiz: [
            { q: "What pH value is considered neutral?", options: ["0", "7", "14", "10"], correct: 1 },
            { q: "Which ion do acids release in water?", options: ["OH⁻", "H⁺", "Na⁺", "Cl⁻"], correct: 1 },
            { q: "Which of these is an everyday use of a base?", options: ["Vinegar in cooking", "Antacid to neutralise stomach acid", "Lemon juice in tea", "Battery acid"], correct: 1 },
            { type: "truefalse", q: "A solution with pH 3 is more acidic than a solution with pH 5.", correct: true, explain: "Lower pH means more acidic — pH 3 has a higher H⁺ concentration than pH 5." },
          ],
        },
      ],
    },
    {
      id: "m3",
      number: 3,
      section: "Week 3",
      title: "Balancing Chemical Equations",
      description: "Steps to balance equations, the Law of Conservation of Mass, and converting experiments into word and chemical equations.",
      lessons: [
        {
          id: "3.1",
          title: "The Law of Conservation of Mass",
          blocks: [
            { type: "p", text: "The **Law of Conservation of Mass** states that in a chemical reaction, matter is neither created nor destroyed. The total mass of the reactants equals the total mass of the products. This is why chemical equations must be **balanced** — the number of atoms of each element must be the same on both sides." },
            { type: "term", term: "Law of Conservation of Mass", definition: "The principle that mass is neither created nor destroyed in a chemical reaction; total mass of reactants equals total mass of products." },
            { type: "p", text: "Example: 2H₂ + O₂ → 2H₂O. Left side: 4 H atoms, 2 O atoms. Right side: 4 H atoms, 2 O atoms. Mass is conserved." },
            { type: "check", qtype: "truefalse", q: "In a balanced chemical equation, the number of atoms of each element must be the same on both sides.", correct: true, explain: "Exactly — this ensures mass is conserved according to the Law of Conservation of Mass." },
            { type: "h", text: "Why balancing matters" },
            { type: "p", text: "Balancing doesn't change what reacts or what forms — it just ensures the **ratio** of molecules is correct so that no atoms are 'lost' or 'created'. This is essential for predicting how much of each substance is needed or produced in a reaction." },
            { type: "callout", text: "One-line version: **Balanced equation = same number of each type of atom on both sides = mass conserved.**" },
          ],
          quiz: [
            { q: "What does the Law of Conservation of Mass state?", options: ["Mass can be created in a reaction", "Mass can be destroyed in a reaction", "Mass is neither created nor destroyed in a reaction", "Mass changes randomly in a reaction"], correct: 2 },
            { q: "In a balanced equation, what must be equal on both sides?", options: ["Only the number of molecules", "Only the number of compounds", "The number of atoms of each element", "The physical states only"], correct: 2 },
            { q: "Which equation correctly shows conservation of mass for water formation?", options: ["H₂ + O₂ → H₂O", "2H₂ + O₂ → 2H₂O", "H₂ + 2O₂ → 2H₂O", "2H₂ + 2O₂ → H₂O"], correct: 1 },
            { type: "truefalse", q: "Balancing a chemical equation changes the identities of the reactants and products.", correct: false, explain: "Balancing only changes the coefficients (ratios), not the chemical formulas or identities." },
          ],
        },
        {
          id: "3.2",
          title: "Steps to Balance a Chemical Equation",
          blocks: [
            { type: "p", text: "Balancing equations follows a clear procedure. You adjust **coefficients** (numbers in front of formulas), never subscripts (which would change the substance)." },
            { type: "h", text: "Step-by-step method" },
            { type: "list", items: [
              "**Step 1**: Write the skeleton equation with correct formulas for reactants and products.",
              "**Step 2**: Count the atoms of each element on both sides.",
              "**Step 3**: Start with the most complex molecule or an element that appears in only one reactant and one product.",
              "**Step 4**: Add coefficients to balance that element, then recount all atoms.",
              "**Step 5**: Repeat for other elements, leaving single elements (like O₂) for last.",
              "**Step 6**: Check that all atoms balance and coefficients are in the simplest whole-number ratio.",
            ]},
            { type: "p", text: "Example: Balancing Mg + O₂ → MgO. Left: Mg=1, O=2. Right: Mg=1, O=1. Add a 2 in front of MgO: Mg + O₂ → 2MgO. Now O is balanced (2 each), but Mg is 1 vs 2. Add a 2 in front of Mg: 2Mg + O₂ → 2MgO. Now both Mg and O are balanced." },
            { type: "check", q: "When balancing equations, what should you change?", options: ["Subscripts in formulas", "Coefficients in front of formulas", "The chemical formulas themselves", "The arrow direction"], correct: 1, explain: "You change COEFFICIENTS only — subscripts define the substance and cannot be altered." },
            { type: "callout", text: "Golden rule: **Never change subscripts.** Only coefficients go in front of whole formulas." },
          ],
          quiz: [
            { q: "What is the first step in balancing a chemical equation?", options: ["Add coefficients randomly", "Write the skeleton equation with correct formulas", "Change subscripts to balance atoms", "Ignore the products"], correct: 1 },
            { q: "In the equation 2Mg + O₂ → 2MgO, how many oxygen atoms are on each side?", options: ["1", "2", "3", "4"], correct: 1 },
            { q: "Which element should you typically balance LAST?", options: ["Carbon", "Hydrogen", "Oxygen (when it appears as O₂)", "Metals"], correct: 2 },
            { type: "truefalse", q: "Coefficients should be reduced to the simplest whole-number ratio after balancing.", correct: true, explain: "Yes — e.g. 2H₂ + O₂ → 2H₂O is preferred over 4H₂ + 2O₂ → 4H₂O." },
          ],
        },
        {
          id: "3.3",
          title: "From Experiments to Balanced Equations",
          blocks: [
            { type: "p", text: "In practical chemistry, you often start with a description of what happened, then convert it step-by-step into a balanced chemical equation." },
            { type: "h", text: "Worked example: Burning magnesium" },
            { type: "list", items: [
              "**Observation**: A strip of magnesium burns with a bright white flame, leaving a white powder.",
              "**Word equation**: Magnesium + Oxygen → Magnesium oxide.",
              "**Skeleton equation**: Mg + O₂ → MgO.",
              "**Balanced equation**: 2Mg + O₂ → 2MgO.",
            ]},
            { type: "p", text: "Another example: Sodium reacting with water produces sodium hydroxide and hydrogen gas." },
            { type: "list", items: [
              "Word: Sodium + Water → Sodium hydroxide + Hydrogen.",
              "Skeleton: Na + H₂O → NaOH + H₂.",
              "Balanced: 2Na + 2H₂O → 2NaOH + H₂.",
            ]},
            { type: "check", q: "In the balanced equation for sodium + water, how many H₂ molecules are produced?", options: ["1", "2", "3", "4"], correct: 0, explain: "2Na + 2H₂O → 2NaOH + H₂ produces 1 H₂ molecule per 2 Na atoms." },
            { type: "callout", text: "Practical workflow: **observe → word equation → formulas → balance.** Each step makes the description more precise." },
          ],
          quiz: [
            { q: "What is the first step when converting an experiment into a chemical equation?", options: ["Balance the equation immediately", "Write a word equation", "Look up molar masses", "Ignore the products"], correct: 1 },
            { q: "In the reaction of sodium with water, what gas is produced?", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], correct: 1 },
            { q: "What is the balanced equation for magnesium burning in oxygen?", options: ["Mg + O₂ → MgO", "2Mg + O₂ → 2MgO", "Mg + 2O₂ → MgO₂", "2Mg + 2O₂ → 2MgO"], correct: 1 },
            { type: "type", q: "Write the balanced equation for: hydrogen + oxygen → water.", accepted: ["2H2 + O2 -> 2H2O", "2H₂ + O₂ → 2H₂O"], explain: "2H₂ + O₂ → 2H₂O balances H and O on both sides." },
          ],
        },
      ],
    },
    {
      id: "m4",
      number: 4,
      section: "Week 4",
      title: "Types of Chemical Reactions",
      description: "Write and balance equations for synthesis, decomposition, respiration, corrosion, combustion, and acid reactions.",
      lessons: [
        {
          id: "4.1",
          title: "Synthesis and Decomposition Reactions",
          blocks: [
            { type: "p", text: "Two fundamental reaction types are **synthesis** (building up) and **decomposition** (breaking down)." },
            { type: "h", text: "Synthesis (combination)" },
            { type: "p", text: "In a synthesis reaction, two or more substances combine to form a single product. General form: A + B → AB." },
            { type: "list", items: [
              "Example: 2Mg + O₂ → 2MgO (magnesium + oxygen → magnesium oxide).",
              "Example: 2H₂ + O₂ → 2H₂O (hydrogen + oxygen → water).",
            ]},
            { type: "h", text: "Decomposition" },
            { type: "p", text: "In a decomposition reaction, one compound breaks down into two or more simpler substances. General form: AB → A + B." },
            { type: "list", items: [
              "Example: 2H₂O → 2H₂ + O₂ (water decomposes into hydrogen and oxygen).",
              "Example: CaCO₃ → CaO + CO₂ (calcium carbonate decomposes on heating).",
            ]},
            { type: "check", qtype: "truefalse", q: "In a synthesis reaction, multiple reactants form a single product.", correct: true, explain: "Synthesis = combination: A + B → AB." },
            { type: "callout", text: "Patterns: **synthesis = combine → one product; decomposition = one reactant → multiple products.**" },
          ],
          quiz: [
            { q: "What type of reaction is 2Mg + O₂ → 2MgO?", options: ["Decomposition", "Synthesis", "Combustion", "Neutralisation"], correct: 1 },
            { q: "Which equation represents a decomposition reaction?", options: ["2H₂ + O₂ → 2H₂O", "CaCO₃ → CaO + CO₂", "HCl + NaOH → NaCl + H₂O", "CH₄ + 2O₂ → CO₂ + 2H₂O"], correct: 1 },
            { q: "In a synthesis reaction, how many products are formed?", options: ["One", "Two", "Three", "Variable"], correct: 0 },
            { type: "truefalse", q: "2H₂O → 2H₂ + O₂ is a decomposition reaction.", correct: true, explain: "One compound (water) breaks into two simpler substances (hydrogen and oxygen)." },
          ],
        },
        {
          id: "4.2",
          title: "Combustion, Respiration, and Corrosion",
          blocks: [
            { type: "p", text: "Three important reaction types that all involve oxygen are **combustion**, **respiration**, and **corrosion**." },
            { type: "h", text: "Combustion" },
            { type: "p", text: "Combustion is rapid reaction with oxygen, usually releasing heat and light. For hydrocarbons, the products are carbon dioxide and water." },
            { type: "list", items: [
              "Example: CH₄ + 2O₂ → CO₂ + 2H₂O (methane combustion).",
              "Example: C₃H₈ + 5O₂ → 3CO₂ + 4H₂O (propane combustion).",
            ]},
            { type: "h", text: "Respiration" },
            { type: "p", text: "Cellular respiration is the controlled 'burning' of glucose in living cells to release energy." },
            { type: "list", items: [
              "Equation: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy.",
              "This is essentially a slow, controlled combustion of glucose.",
            ]},
            { type: "h", text: "Corrosion" },
            { type: "p", text: "Corrosion is the slow reaction of metals with oxygen (and often water), forming oxides or hydroxides. Rusting of iron is the most familiar example." },
            { type: "list", items: [
              "Simplified: 4Fe + 3O₂ → 2Fe₂O₃ (iron + oxygen → iron(III) oxide, rust).",
              "Water and electrolytes speed up the process.",
            ]},
            { type: "check", q: "Which reaction type is essentially a controlled 'burning' of glucose in cells?", options: ["Combustion", "Respiration", "Corrosion", "Decomposition"], correct: 1, explain: "Respiration is the controlled oxidation of glucose to release energy." },
            { type: "callout", text: "Common thread: **all three involve oxygen; combustion is fast, respiration is controlled, corrosion is slow.**" },
          ],
          quiz: [
            { q: "What are the typical products of complete hydrocarbon combustion?", options: ["CO and H₂", "CO₂ and H₂O", "C and H₂", "CO₂ only"], correct: 1 },
            { q: "Which equation represents cellular respiration?", options: ["CH₄ + 2O₂ → CO₂ + 2H₂O", "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O", "4Fe + 3O₂ → 2Fe₂O₃", "CaCO₃ → CaO + CO₂"], correct: 1 },
            { q: "Rusting of iron is an example of:", options: ["Combustion", "Respiration", "Corrosion", "Decomposition"], correct: 2 },
            { type: "truefalse", q: "Combustion reactions are typically exothermic.", correct: true, explain: "Combustion releases large amounts of energy as heat and light." },
          ],
        },
        {
          id: "4.3",
          title: "Acid Reactions",
          blocks: [
            { type: "p", text: "Acids react in predictable ways with metals, carbonates, bases, and metal oxides. Each type follows a characteristic pattern." },
            { type: "h", text: "Acids on metals" },
            { type: "list", items: [
              "General: Acid + metal → salt + hydrogen gas.",
              "Example: 2HCl + Zn → ZnCl₂ + H₂.",
            ]},
            { type: "h", text: "Acids on carbonates" },
            { type: "list", items: [
              "General: Acid + carbonate → salt + water + carbon dioxide.",
              "Example: 2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂.",
            ]},
            { type: "h", text: "Neutralisation (acids on bases)" },
            { type: "list", items: [
              "General: Acid + base → salt + water.",
              "Example: HCl + NaOH → NaCl + H₂O.",
            ]},
            { type: "h", text: "Acids on metal oxides" },
            { type: "list", items: [
              "General: Acid + metal oxide → salt + water.",
              "Example: 2HCl + CuO → CuCl₂ + H₂O.",
            ]},
            { type: "check", qtype: "truefalse", q: "When an acid reacts with a carbonate, carbon dioxide gas is produced.", correct: true, explain: "Acid + carbonate → salt + water + CO₂ gas." },
            { type: "callout", text: "Patterns to memorise: **acid + metal → salt + H₂; acid + carbonate → salt + H₂O + CO₂; acid + base → salt + H₂O.**" },
          ],
          quiz: [
            { q: "What are the products when an acid reacts with a metal?", options: ["Salt and oxygen", "Salt and hydrogen gas", "Water and carbon dioxide", "Metal oxide and hydrogen"], correct: 1 },
            { q: "What are the products when an acid reacts with a carbonate?", options: ["Salt and hydrogen only", "Salt, water, and carbon dioxide", "Salt and oxygen", "Metal and water"], correct: 1 },
            { q: "Which equation represents a neutralisation reaction?", options: ["HCl + NaOH → NaCl + H₂O", "2HCl + Zn → ZnCl₂ + H₂", "CaCO₃ → CaO + CO₂", "CH₄ + 2O₂ → CO₂ + 2H₂O"], correct: 0 },
            { type: "multi", q: "Select all the products formed when hydrochloric acid reacts with calcium carbonate.", options: ["Calcium chloride", "Water", "Carbon dioxide", "Hydrogen gas"], correct: [0, 1, 2], explain: "2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂ produces salt, water, and CO₂." },
          ],
        },
        {
          id: "4.4",
          title: "Metals and Water",
          blocks: [
            { type: "p", text: "Some metals react with water to form a metal hydroxide and hydrogen gas. The reactivity depends on the metal's position in the reactivity series." },
            { type: "h", text: "General pattern" },
            { type: "list", items: [
              "Metal + water → metal hydroxide + hydrogen gas.",
              "Example (sodium): 2Na + 2H₂O → 2NaOH + H₂.",
              "Example (potassium): 2K + 2H₂O → 2KOH + H₂.",
            ]},
            { type: "p", text: "Less reactive metals (like magnesium) react very slowly with cold water but more readily with steam, forming the oxide instead of the hydroxide in some cases." },
            { type: "check", q: "What gas is produced when sodium reacts with water?", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], correct: 1, explain: "2Na + 2H₂O → 2NaOH + H₂ produces hydrogen gas." },
            { type: "callout", text: "Key reaction: **reactive metal + water → metal hydroxide + H₂.**" },
          ],
          quiz: [
            { q: "What type of compound is formed when sodium reacts with water?", options: ["Sodium oxide", "Sodium hydroxide", "Sodium carbonate", "Sodium chloride"], correct: 1 },
            { q: "Which gas is produced when reactive metals react with water?", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Chlorine"], correct: 1 },
            { q: "Which metal reacts most vigorously with water?", options: ["Copper", "Iron", "Sodium", "Silver"], correct: 2 },
            { type: "truefalse", q: "All metals react rapidly with cold water.", correct: false, explain: "Only very reactive metals (e.g. Na, K) react vigorously; many react slowly or not at all." },
          ],
        },
      ],
    },
    {
      id: "m5",
      number: 5,
      section: "Week 5",
      title: "Energy Changes and Reaction Rates",
      description: "Exothermic vs endothermic reactions, collision theory, and factors affecting reaction rates with practical investigations.",
      lessons: [
        {
          id: "5.1",
          title: "Exothermic and Endothermic Reactions",
          blocks: [
            { type: "p", text: "Chemical reactions involve energy changes. Some release energy to the surroundings; others absorb energy from the surroundings. These are called **exothermic** and **endothermic** reactions, respectively." },
            { type: "term", term: "Exothermic reaction", definition: "A reaction that releases energy (usually as heat) to the surroundings. The products have less energy than the reactants." },
            { type: "term", term: "Endothermic reaction", definition: "A reaction that absorbs energy from the surroundings. The products have more energy than the reactants." },
            { type: "h", text: "Everyday examples" },
            { type: "list", items: [
              "**Exothermic**: Combustion (burning fuels), respiration, neutralisation, corrosion. These feel hot or release heat.",
              "**Endothermic**: Photosynthesis, dissolving ammonium nitrate in water (cold packs), thermal decomposition. These feel cold or require heat input.",
            ]},
            { type: "check", qtype: "truefalse", q: "In an exothermic reaction, the surroundings get warmer.", correct: true, explain: "Exothermic reactions release energy, often as heat, warming the surroundings." },
            { type: "h", text: "Energy diagrams" },
            { type: "p", text: "On an energy profile, exothermic reactions show products at a lower energy level than reactants (energy released). Endothermic reactions show products at a higher energy level (energy absorbed)." },
            { type: "callout", text: "Simple test: **reaction feels hot → exothermic; feels cold → endothermic.**" },
          ],
          quiz: [
            { q: "Which type of reaction releases energy to the surroundings?", options: ["Endothermic", "Exothermic", "Neutral", "Decomposition"], correct: 1 },
            { q: "Which of these is an endothermic process?", options: ["Burning wood", "Respiration", "Photosynthesis", "Rusting iron"], correct: 2 },
            { q: "In an endothermic reaction, how does the energy of products compare to reactants?", options: ["Products have less energy", "Products have more energy", "Energy is the same", "Energy is destroyed"], correct: 1 },
            { type: "truefalse", q: "Combustion reactions are typically exothermic.", correct: true, explain: "Combustion releases large amounts of energy as heat and light." },
          ],
        },
        {
          id: "5.2",
          title: "Particle Theory and Collision Theory",
          blocks: [
            { type: "p", text: "The **particle theory** states that all matter is made of tiny particles in constant motion. **Collision theory** builds on this: for a reaction to occur, particles must collide with sufficient energy and the correct orientation." },
            { type: "term", term: "Collision theory", definition: "The idea that chemical reactions occur when particles collide with enough energy (activation energy) and the correct orientation." },
            { type: "h", text: "Activation energy" },
            { type: "p", text: "Not every collision causes a reaction. Particles must have at least a minimum energy called the **activation energy** to break existing bonds and form new ones. Collisions below this energy simply bounce off." },
            { type: "check", q: "According to collision theory, what two conditions must be met for a reaction?", options: ["Particles must be the same size and shape", "Particles must collide with sufficient energy and correct orientation", "Particles must be at rest", "Particles must be in a vacuum"], correct: 1, explain: "Collisions must have enough energy AND the right orientation to react." },
            { type: "h", text: "Link to reaction rates" },
            { type: "p", text: "The **rate of reaction** depends on how often successful collisions occur. Anything that increases the frequency or energy of collisions will increase the rate." },
            { type: "callout", text: "Core idea: **more frequent, higher-energy collisions → faster reaction.**" },
          ],
          quiz: [
            { q: "What is activation energy?", options: ["The energy released in a reaction", "The minimum energy needed for a reaction to occur", "The energy of the products", "The energy of the reactants"], correct: 1 },
            { q: "According to collision theory, what happens if particles collide without enough energy?", options: ["They react anyway", "They bounce off without reacting", "They form a catalyst", "They change state"], correct: 1 },
            { q: "What does the rate of a reaction measure?", options: ["How much energy is released", "How fast reactants turn into products", "The temperature change", "The final mass"], correct: 1 },
            { type: "truefalse", q: "All collisions between reactant particles result in a reaction.", correct: false, explain: "Only collisions with sufficient energy and correct orientation lead to reactions." },
          ],
        },
        {
          id: "5.3",
          title: "Factors Affecting Reaction Rates",
          blocks: [
            { type: "p", text: "Several factors influence how often successful collisions occur, and therefore how fast a reaction proceeds." },
            { type: "h", text: "Key factors" },
            { type: "list", items: [
              "**Concentration**: Higher concentration means more particles in a given volume → more frequent collisions → faster rate.",
              "**Temperature**: Higher temperature means particles move faster and collide more often AND with more energy → more collisions exceed activation energy → faster rate.",
              "**Surface area**: For solids, breaking into smaller pieces increases surface area → more particles exposed → more collisions → faster rate.",
              "**Agitation (stirring)**: Mixing brings fresh reactant particles together more often → increases collision frequency.",
              "**Catalysts**: Substances that lower the activation energy without being consumed → more collisions are successful → faster rate.",
            ]},
            { type: "check", qtype: "truefalse", q: "A catalyst is consumed in a reaction and cannot be reused.", correct: false, explain: "Catalysts are NOT consumed — they speed up reactions and can be used repeatedly." },
            { type: "h", text: "Practical example: Magnesium and hydrochloric acid" },
            { type: "p", text: "In a rate experiment, you might measure how quickly hydrogen gas is produced when magnesium reacts with HCl. Increasing acid concentration, raising temperature, or using powdered magnesium (more surface area) would all increase the rate of gas production." },
            { type: "callout", text: "Rate rule: **increase concentration, temperature, surface area, agitation, or add a catalyst → faster reaction.**" },
          ],
          quiz: [
            { q: "Which factor does NOT increase reaction rate?", options: ["Higher concentration", "Lower temperature", "Increased surface area", "Adding a catalyst"], correct: 1 },
            { q: "How does a catalyst increase reaction rate?", options: ["By increasing temperature", "By lowering activation energy", "By increasing concentration", "By changing the products"], correct: 1 },
            { q: "Why does powdered magnesium react faster than a strip?", options: ["It has less mass", "It has more surface area", "It is colder", "It is less reactive"], correct: 1 },
            { type: "multi", q: "Select all factors that increase reaction rate.", options: ["Higher temperature", "Lower concentration", "Increased surface area", "Stirring/agitation"], correct: [0, 2, 3], explain: "Higher temperature, increased surface area, and agitation all increase collision frequency or energy." },
          ],
        },
        {
          id: "5.4",
          title: "Designing Rate Experiments",
          blocks: [
            { type: "p", text: "To test hypotheses about reaction rates, you design fair experiments where only one factor (the **independent variable**) is changed, while others are controlled. You measure the effect on the **dependent variable** (e.g. time taken, volume of gas produced)." },
            { type: "term", term: "Independent variable", definition: "The factor you deliberately change in an experiment to test its effect." },
            { type: "term", term: "Dependent variable", definition: "The factor you measure in response to changes in the independent variable." },
            { type: "h", text: "Example: Effect of concentration on rate" },
            { type: "list", items: [
              "**Independent variable**: Concentration of HCl.",
              "**Dependent variable**: Time taken for magnesium to completely react (or volume of H₂ gas produced in a fixed time).",
              "**Controlled variables**: Mass/length of magnesium, temperature, volume of acid, same apparatus.",
            ]},
            { type: "check", q: "In an experiment testing temperature's effect on rate, what is the independent variable?", options: ["Volume of gas produced", "Temperature", "Time taken", "Mass of reactant"], correct: 1, explain: "Temperature is what you're deliberately changing to see its effect." },
            { type: "h", text: "Safety and risk assessment" },
            { type: "p", text: "Rate experiments often involve acids, gases, or heat. A proper risk assessment identifies hazards (e.g. corrosive acids, flammable hydrogen), controls (goggles, gloves, ventilation), and emergency procedures." },
            { type: "callout", text: "Experimental design mantra: **change one thing (independent), measure one thing (dependent), keep everything else constant (controlled).**" },
          ],
          quiz: [
            { q: "What is the dependent variable in a rate experiment?", options: ["The factor you change", "The factor you measure", "The factor you keep constant", "The equipment used"], correct: 1 },
            { q: "Which safety equipment is essential when handling acids?", options: ["Sandals", "Safety goggles", "Shorts", "No gloves"], correct: 1 },
            { q: "In testing the effect of surface area on rate, what should be kept constant?", options: ["Particle size", "Temperature and concentration", "Type of solid only", "Nothing"], correct: 1 },
            { type: "truefalse", q: "A fair test changes only one variable at a time.", correct: true, explain: "Yes — changing multiple variables at once makes it impossible to know which caused the effect." },
          ],
        },
      ],
    },
    {
      id: "m6",
      number: 6,
      section: "Week 6",
      title: "Organic Chemistry and Polymers",
      description: "Distinguish organic and inorganic compounds, define hydrocarbons, use IUPAC naming for alkanes, alkenes, and alkyl halides, and describe polymers.",
      lessons: [
        {
          id: "6.1",
          title: "Organic vs Inorganic Compounds",
          blocks: [
            { type: "p", text: "Compounds are broadly classified as **organic** or **inorganic**. Organic compounds contain carbon-hydrogen (C–H) bonds and are associated with living things and their derivatives. Inorganic compounds generally do not contain C–H bonds." },
            { type: "term", term: "Organic compound", definition: "A compound that contains carbon-hydrogen (C–H) bonds, typically associated with living organisms and their derivatives." },
            { type: "term", term: "Inorganic compound", definition: "A compound that typically does not contain carbon-hydrogen bonds, including minerals, salts, metals, and simple carbon compounds like CO₂." },
            { type: "h", text: "Examples" },
            { type: "list", items: [
              "**Organic**: Methane (CH₄), glucose (C₆H₁₂O₆), ethanol (C₂H₅OH), plastics (polymers).",
              "**Inorganic**: Water (H₂O), sodium chloride (NaCl), carbon dioxide (CO₂), sulfuric acid (H₂SO₄).",
            ]},
            { type: "check", qtype: "truefalse", q: "All carbon-containing compounds are organic.", correct: false, explain: "Some carbon compounds like CO₂ and carbonates are classified as inorganic." },
            { type: "callout", text: "Rule of thumb: **C–H bonds → organic; no C–H bonds → usually inorganic** (with a few exceptions)." },
          ],
          quiz: [
            { q: "Which of these is an organic compound?", options: ["NaCl", "H₂O", "CH₄", "CO₂"], correct: 2 },
            { q: "What type of bond is characteristic of organic compounds?", options: ["C–O", "C–H", "Na–Cl", "H–O"], correct: 1 },
            { q: "Which is an inorganic compound?", options: ["Glucose", "Ethanol", "Sodium chloride", "Methane"], correct: 2 },
            { type: "truefalse", q: "Plastics are examples of organic compounds.", correct: true, explain: "Plastics are polymers made of long chains of carbon-based (organic) molecules." },
          ],
        },
        {
          id: "6.2",
          title: "Hydrocarbons",
          blocks: [
            { type: "p", text: "**Hydrocarbons** are organic compounds made only of hydrogen and carbon. They're grouped into families based on the types of bonds between carbon atoms." },
            { type: "term", term: "Hydrocarbon", definition: "An organic compound consisting only of hydrogen and carbon atoms." },
            { type: "h", text: "Main families" },
            { type: "list", items: [
              "**Alkanes**: Single bonds only (saturated). General formula CₙH₂ₙ₊₂. Examples: methane (CH₄), ethane (C₂H₆), propane (C₃H₈).",
              "**Alkenes**: At least one carbon-carbon double bond (unsaturated). General formula CₙH₂ₙ. Examples: ethene (C₂H₄), propene (C₃H₆).",
              "**Alkynes**: At least one carbon-carbon triple bond. General formula CₙH₂ₙ₋₂. Examples: ethyne (C₂H₂).",
            ]},
            { type: "check", q: "What is the general formula for alkanes?", options: ["CₙH₂ₙ", "CₙH₂ₙ₊₂", "CₙH₂ₙ₋₂", "CₙHₙ"], correct: 1, explain: "Alkanes have only single bonds and follow CₙH₂ₙ₊₂." },
            { type: "callout", text: "Family patterns: **alkanes = single bonds; alkenes = at least one double bond; alkynes = at least one triple bond.**" },
          ],
          quiz: [
            { q: "What type of bonds do alkanes contain?", options: ["Only double bonds", "Only single bonds", "Only triple bonds", "Both single and double bonds"], correct: 1 },
            { q: "What is the IUPAC name for C₂H₆?", options: ["Methane", "Ethane", "Propane", "Butane"], correct: 1 },
            { q: "Which family has at least one C=C double bond?", options: ["Alkanes", "Alkenes", "Alkynes", "Aromatic"], correct: 1 },
            { type: "type", q: "What is the general formula for alkenes?", accepted: ["CnH2n", "CₙH₂ₙ"], explain: "Alkenes have one double bond and follow CₙH₂ₙ." },
          ],
        },
        {
          id: "6.3",
          title: "IUPAC Nomenclature",
          blocks: [
            { type: "p", text: "The **IUPAC** system gives each organic compound a unique, systematic name based on the longest carbon chain and the positions of branches or functional groups." },
            { type: "h", text: "Naming alkanes" },
            { type: "list", items: [
              "Find the longest continuous carbon chain (parent name: methane, ethane, propane, etc.).",
              "Number the chain to give substituents the lowest possible numbers.",
              "Name and number each branch (e.g. methyl, ethyl).",
              "Combine: number–substituent + parent name (e.g. 2-methylpropane).",
            ]},
            { type: "h", text: "Alkenes and alkyl halides" },
            { type: "list", items: [
              "For alkenes, indicate the position of the double bond (e.g. but-1-ene, but-2-ene).",
              "For alkyl halides, name the halogen as a substituent (e.g. chloro-, bromo-) with its position.",
            ]},
            { type: "check", qtype: "truefalse", q: "In IUPAC naming, the longest carbon chain determines the parent name.", correct: true, explain: "The longest continuous chain gives the base name (methane, ethane, propane, etc.)." },
            { type: "callout", text: "Naming pattern: **position–substituent + parent chain** (e.g. 2-methylbutane, 1-chloropropane)." },
          ],
          quiz: [
            { q: "What determines the parent name in IUPAC naming?", options: ["Number of branches", "Longest carbon chain", "Type of halogen", "Position of double bond only"], correct: 1 },
            { q: "What is the IUPAC name for CH₃CH₂CH₃?", options: ["Methane", "Ethane", "Propane", "Butane"], correct: 2 },
            { q: "How is a chlorine substituent named in IUPAC?", options: ["Chloride", "Chloro-", "Chlorine", "Chlorate"], correct: 1 },
            { type: "type", q: "Name this alkane: CH₃CH(CH₃)CH₃.", accepted: ["2-methylpropane", "2 methylpropane"], explain: "Three-carbon chain (propane) with a methyl on carbon 2 → 2-methylpropane." },
          ],
        },
        {
          id: "6.4",
          title: "Polymers",
          blocks: [
            { type: "p", text: "**Polymers** are large molecules made by joining many small repeating units called **monomers**. They can be natural (e.g. proteins, DNA) or synthetic (e.g. plastics like polyethylene)." },
            { type: "term", term: "Polymer", definition: "A large molecule made of many repeating smaller units (monomers) bonded together." },
            { type: "h", text: "Raw materials" },
            { type: "p", text: "Most synthetic polymers are made from **petrochemicals** — chemicals derived from crude oil or natural gas. Ethene (C₂H₄), for example, is polymerised to make polyethylene (polythene)." },
            { type: "check", qtype: "truefalse", q: "Polymers are made from monomers.", correct: true, explain: "Polymers are long chains formed by linking many monomer units together." },
            { type: "h", text: "Properties of polymers" },
            { type: "list", items: [
              "**Strength**: Many polymers are strong yet lightweight (e.g. nylon, Kevlar).",
              "**Flexibility**: Some are flexible and stretchy (e.g. rubber, polyethylene).",
              "**Chemical resistance**: Many resist corrosion and chemicals (e.g. PVC).",
              "**Insulation**: Good electrical and thermal insulators (e.g. plastic coatings on wires).",
            ]},
            { type: "callout", text: "Key idea: **monomers → polymerisation → polymers** with useful properties like strength, flexibility, and resistance." },
          ],
          quiz: [
            { q: "What are polymers made from?", options: ["Atoms only", "Monomers", "Metals", "Salts"], correct: 1 },
            { q: "Which raw material is commonly used to make synthetic polymers?", options: ["Water", "Petrochemicals", "Sand", "Salt"], correct: 1 },
            { q: "Which property is typical of many polymers?", options: ["High electrical conductivity", "Chemical resistance", "High density", "Brittleness only"], correct: 1 },
            { type: "truefalse", q: "Polyethylene is made from ethene monomers.", correct: true, explain: "Ethene (C₂H₄) molecules polymerise to form polyethylene." },
          ],
        },
      ],
    },
    {
      id: "m7",
      number: 7,
      section: "Week 7",
      title: "Nuclear Chemistry",
      description: "Big Bang nucleosynthesis, unstable nuclei, alpha and beta decay, half-life, fission, fusion, and environmental impacts.",
      lessons: [
        {
          id: "7.1",
          title: "Formation of the First Elements",
          blocks: [
            { type: "p", text: "After the Big Bang, the universe was initially too hot for atoms to form. As it cooled, protons and neutrons combined to form the first nuclei — mostly hydrogen and helium, with traces of lithium. This process is called **Big Bang nucleosynthesis**." },
            { type: "term", term: "Big Bang nucleosynthesis", definition: "The process in the early universe where the first light elements (H, He, Li) formed from protons and neutrons as the universe cooled." },
            { type: "check", q: "Which elements were primarily formed in Big Bang nucleosynthesis?", options: ["Carbon and oxygen", "Hydrogen and helium", "Iron and nickel", "Uranium and plutonium"], correct: 1, explain: "The early universe produced mostly H and He, with tiny amounts of Li." },
            { type: "callout", text: "First elements: **mostly hydrogen and helium, formed as the early universe cooled.**" },
          ],
          quiz: [
            { q: "What process formed the first elements after the Big Bang?", options: ["Combustion", "Big Bang nucleosynthesis", "Respiration", "Corrosion"], correct: 1 },
            { q: "Which element was NOT significantly formed in the early universe?", options: ["Hydrogen", "Helium", "Lithium", "Carbon"], correct: 3 },
            { q: "What were the main products of Big Bang nucleosynthesis?", options: ["Heavy metals", "Hydrogen and helium", "Organic molecules", "Water"], correct: 1 },
            { type: "truefalse", q: "The early universe was initially too hot for atoms to form.", correct: true, explain: "It had to cool enough for protons and neutrons to combine into nuclei." },
          ],
        },
        {
          id: "7.2",
          title: "Unstable Nuclei and Radioactive Decay",
          blocks: [
            { type: "p", text: "Some nuclei are **unstable** due to an imbalance of protons and neutrons. They undergo **radioactive decay** to become more stable, emitting radiation in the process." },
            { type: "h", text: "Alpha decay" },
            { type: "list", items: [
              "Emission of an alpha particle (⁴₂He nucleus).",
              "Reduces atomic number by 2 and mass number by 4.",
              "Example: ²³⁸₉₂U → ²³⁴₉₀Th + ⁴₂He.",
            ]},
            { type: "h", text: "Beta decay" },
            { type: "list", items: [
              "A neutron converts to a proton + electron; the electron (beta particle) is emitted.",
              "Atomic number increases by 1, mass number stays the same.",
              "Example: ¹⁴₆C → ¹⁴₇N + ⁰₋₁e.",
            ]},
            { type: "check", qtype: "truefalse", q: "In beta decay, the mass number changes.", correct: false, explain: "In beta decay, mass number stays the same; atomic number increases by 1." },
            { type: "callout", text: "Decay patterns: **alpha → mass −4, atomic −2; beta → mass same, atomic +1.**" },
          ],
          quiz: [
            { q: "What happens in alpha decay?", options: ["Atomic number increases by 1", "Mass number decreases by 4 and atomic number by 2", "Mass number increases", "No change in nucleus"], correct: 1 },
            { q: "In beta decay, what happens to the atomic number?", options: ["Decreases by 2", "Increases by 1", "Decreases by 1", "Stays the same"], correct: 1 },
            { q: "What is emitted in alpha decay?", options: ["An electron", "A helium nucleus", "A neutron", "A photon"], correct: 1 },
            { type: "type", q: "Write the symbol for an alpha particle.", accepted: ["4_2He", "⁴₂He", "alpha particle"], explain: "An alpha particle is a helium nucleus: ⁴₂He." },
          ],
        },
        {
          id: "7.3",
          title: "Half-Life and Applications of Radioisotopes",
          blocks: [
            { type: "p", text: "The **half-life** of a radioactive isotope is the time it takes for half of the atoms in a sample to decay. It's a constant for each isotope, unaffected by temperature, pressure, or chemical state." },
            { type: "term", term: "Half-life", definition: "The time required for half of the radioactive atoms in a sample to undergo decay." },
            { type: "h", text: "Uses of radioisotopes" },
            { type: "list", items: [
              "**Medicine**: Technetium-99m for imaging; iodine-131 for thyroid treatment; cobalt-60 for radiotherapy.",
              "**Industry**: Checking for leaks in pipes, measuring thickness of materials, sterilising equipment.",
              "**Environmental monitoring**: Tracing pollution, studying water flow, carbon-14 dating of archaeological samples.",
            ]},
            { type: "check", qtype: "truefalse", q: "Half-life changes with temperature.", correct: false, explain: "Half-life is constant for a given isotope and is not affected by external conditions." },
            { type: "h", text: "Societal considerations" },
            { type: "p", text: "While radioisotopes offer huge benefits, they also pose risks: radiation exposure, long-lived waste, and potential misuse. Safe handling, storage, and disposal are critical." },
            { type: "callout", text: "Balance: **benefits (medicine, industry, research) vs risks (radiation, waste, safety).**" },
          ],
          quiz: [
            { q: "What is half-life?", options: ["Time for all atoms to decay", "Time for half the atoms to decay", "Time for mass to halve", "Time for energy to halve"], correct: 1 },
            { q: "Which isotope is used in carbon dating?", options: ["Uranium-238", "Carbon-14", "Iodine-131", "Cobalt-60"], correct: 1 },
            { q: "Which is a medical use of radioisotopes?", options: ["Making plastics", "Radiotherapy for cancer", "Producing electricity only", "Cleaning water only"], correct: 1 },
            { type: "truefalse", q: "Radioisotopes are used in industry to check for pipe leaks.", correct: true, explain: "Yes — radioisotopes can trace flow and detect leaks in pipelines." },
          ],
        },
        {
          id: "7.4",
          title: "Nuclear Fission and Fusion",
          blocks: [
            { type: "p", text: "Two major types of nuclear reactions release vast amounts of energy: **fission** (splitting heavy nuclei) and **fusion** (joining light nuclei)." },
            { type: "term", term: "Nuclear fission", definition: "The splitting of a heavy nucleus into lighter nuclei, releasing energy and often neutrons." },
            { type: "term", term: "Nuclear fusion", definition: "The joining of light nuclei to form a heavier nucleus, releasing energy." },
            { type: "h", text: "Fission" },
            { type: "p", text: "In nuclear power plants, uranium-235 nuclei absorb neutrons and split into smaller nuclei (e.g. barium and krypton), releasing energy and more neutrons that can trigger further fissions (a chain reaction)." },
            { type: "p", text: "Example: ²³⁵₉₂U + ¹₀n → ¹⁴¹₅₆Ba + ⁹²₃₆Kr + 3¹₀n + energy." },
            { type: "h", text: "Fusion" },
            { type: "p", text: "Fusion powers the Sun and stars. Under extreme temperature and pressure, hydrogen nuclei fuse to form helium, releasing enormous energy." },
            { type: "p", text: "Example: ²₁H + ³₁H → ⁴₂He + ¹₀n + energy." },
            { type: "check", q: "Which process powers the Sun?", options: ["Fission", "Fusion", "Combustion", "Respiration"], correct: 1, explain: "The Sun's energy comes from fusion of hydrogen into helium." },
            { type: "h", text: "Environmental impacts" },
            { type: "list", items: [
              "**Fission**: Produces long-lived radioactive waste; risk of accidents; uranium mining impacts.",
              "**Fusion**: Produces minimal long-lived waste; no chain reaction risk; but requires extreme conditions not yet sustainably achievable on Earth.",
            ]},
            { type: "callout", text: "Big picture: **fission = split heavy atoms (current power plants); fusion = join light atoms (Sun, future energy).**" },
          ],
          quiz: [
            { q: "What is nuclear fission?", options: ["Joining light nuclei", "Splitting heavy nuclei", "Burning fossil fuels", "Combining molecules"], correct: 1 },
            { q: "Which reaction produces the Sun's energy?", options: ["Fission", "Fusion", "Combustion", "Oxidation"], correct: 1 },
            { q: "What is a major environmental concern with fission?", options: ["No waste produced", "Long-lived radioactive waste", "Too much oxygen", "Excessive water use only"], correct: 1 },
            { type: "truefalse", q: "Fusion reactions produce minimal long-lived radioactive waste compared to fission.", correct: true, explain: "Fusion produces far less long-lived waste, making it potentially cleaner if achievable." },
          ],
        },
      ],
    },
  ],
};
