// Psychology Level 1: Beginner course data.
// This is the ONLY file to touch when adding lessons to this course.
// Shape: modules -> lessons -> content blocks (+ a quiz per lesson).
//
// QUESTION TYPES — every quiz item, and every mid-lesson "check" block,
// can use one of four answer formats by setting `type` (quiz items) or
// `qtype` (check blocks — `type` is already used there to mark it as a
// checkpoint). Leaving it out defaults to "mcq".
//
//   mcq (default)  { q, options, correct, explain? }              — tap one option
//   truefalse      { q, correct: true|false, explain? }           — tap True/False
//   multi          { q, options, correct: [i, j], explain? }      — select ALL that apply
//   type           { q, accepted: ["answer", "alt answer"], explain? } — type the answer
//
// See README.md at the project root for the full block-type reference.

export const psychologyLevel1 = {
  id: "psychology-level-1-beginner",
  title: "Psychology: Level 1 — Beginner",
  tagline: "Foundations of psychology — history, methods, brain, and core concepts.",
  icon: "brain",
  accent: "#7B2D9E",       // purple — used for progress, buttons, highlights
  ink: "#1A1A2E",          // deep navy — used for headers, dark surfaces
  modules: [
    {
      id: "m1",
      number: 1,
      section: "Module 1",
      title: "Introduction to Psychology",
      description: "What psychology is, its history, major perspectives, and career paths.",
      lessons: [
        {
          id: "1.1",
          title: "What Is Psychology?",
          blocks: [
            { type: "p", text: "Psychology is the **scientific study of mind and behaviour**. This definition matters because it tells you exactly what psychologists do: they use scientific methods to understand how people think, feel, and act — both individually and in groups." },
            { type: "term", term: "Psychology", definition: "The scientific study of mind and behaviour, including thoughts, emotions, and actions." },
            { type: "h", text: "Mind vs behaviour" },
            { type: "p", text: "The 'mind' part refers to internal, subjective experiences — thoughts, feelings, perceptions, memories, consciousness. The 'behaviour' part refers to observable actions — what people say and do. Modern psychology studies both, even though early psychologists disagreed about which should be the focus." },
            { type: "h", text: "Psychology vs psychiatry vs counselling" },
            { type: "list", items: [
              "**Psychology**: Scientists and practitioners who study mind and behaviour. Clinical psychologists have doctoral degrees (PhD or PsyD) and provide therapy and assessment, but cannot prescribe medication (in most countries).",
              "**Psychiatry**: Medical doctors (MD) who specialise in mental health. They can prescribe medication and often focus on biological treatments, though many also provide therapy.",
              "**Counselling**: A broader term that includes psychologists, social workers, counsellors, and therapists who provide talk therapy. Training varies from certificates to doctoral degrees.",
            ]},
            { type: "check", qtype: "truefalse", q: "Psychologists can prescribe medication in most countries.", correct: false, explain: "In most countries, psychologists CANNOT prescribe medication — that's psychiatrists (medical doctors). Some US states allow specially trained psychologists to prescribe, but this is the exception." },
            { type: "h", text: "Myths and misconceptions" },
            { type: "list", items: [
              "**Myth**: Psychology is just common sense. **Reality**: Many psychological findings are counterintuitive (e.g. eyewitness testimony is often unreliable, despite feeling certain).",
              "**Myth**: Psychologists can read minds. **Reality**: Psychologists study behaviour and mental processes scientifically — no mind-reading involved.",
              "**Myth**: Psychology only studies mental illness. **Reality**: Psychology covers everything from normal development and learning to happiness, creativity, and peak performance.",
            ]},
            { type: "callout", text: "Key takeaway: **Psychology = scientific study of mind AND behaviour.** It's not just therapy, not just common sense, and definitely not mind-reading." },
          ],
          quiz: [
            { q: "What is psychology?", options: ["The study of mental illness only", "The scientific study of mind and behaviour", "The study of how to read minds", "Common sense about people"], correct: 1 },
            { q: "Who can prescribe medication for mental health conditions?", options: ["Clinical psychologists", "Psychiatrists", "Counsellors", "Social workers"], correct: 1 },
            { q: "Which of these is a common myth about psychology?", options: ["Psychology uses scientific methods", "Psychologists can read minds", "Psychology studies behaviour", "Psychology includes mental processes"], correct: 1 },
            { type: "type", q: "Fill in the blank: Psychology is the scientific study of mind and ______.", accepted: ["behaviour", "behavior"], explain: "Psychology studies both mental processes (mind) and observable actions (behaviour)." },
          ],
        },
        {
          id: "1.2",
          title: "A Brief History of Psychology",
          blocks: [
            { type: "p", text: "Psychology has philosophical roots going back thousands of years, but it only became a distinct scientific discipline in the late 1800s. Understanding this history helps you see why psychology looks the way it does today." },
            { type: "h", text: "Philosophical roots" },
            { type: "p", text: "Ancient philosophers like **Plato** and **Aristotle** asked questions about the mind, knowledge, and human nature that psychologists still debate. **Descartes** (1596–1650) proposed **mind-body dualism** — the idea that mind and body are separate entities that interact. This 'mind-body problem' remains influential today." },
            { type: "term", term: "Mind-body dualism", definition: "Descartes' idea that the mind and body are separate entities that somehow interact." },
            { type: "h", text: "Wilhelm Wundt and structuralism (1879)" },
            { type: "p", text: "In 1879, **Wilhelm Wundt** opened the first psychology laboratory at the University of Leipzig in Germany — often considered the birth of psychology as a science. Wundt used **introspection** (looking inward) to try to identify the basic 'structures' of conscious experience. This approach became known as **structuralism**." },
            { type: "term", term: "Structuralism", definition: "Wundt's approach of breaking conscious experience into its basic components through introspection." },
            { type: "term", term: "Introspection", definition: "Looking inward to examine one's own conscious experiences — Wundt's primary method." },
            { type: "h", text: "William James and functionalism" },
            { type: "p", text: "Around the same time in America, **William James** was developing **functionalism** — the idea that psychology should study the *function* of behaviour and mental processes (how they help us adapt to our environment), not just their structure. James wrote the first major psychology textbook, *The Principles of Psychology* (1890)." },
            { type: "term", term: "Functionalism", definition: "James's approach focusing on how mental activities and behaviours help organisms adapt to their environment." },
            { type: "h", text: "Behaviourism (1920s–1950s)" },
            { type: "p", text: "In the early 20th century, psychologists like **John Watson** and **B.F. Skinner** argued that psychology should be an objective science studying only **observable behaviour**, not unobservable mental processes. This became **behaviourism**, which dominated psychology for decades." },
            { type: "term", term: "Behaviourism", definition: "The perspective that psychology should study only observable behaviour, not mental processes." },
            { type: "h", text: "The cognitive revolution (1960s)" },
            { type: "p", text: "By the 1960s, psychologists realised that ignoring mental processes was too limiting. The **cognitive revolution** brought the study of thinking, memory, language, and problem-solving back into psychology — often using the computer as a model for how the mind processes information." },
            { type: "callout", text: "History timeline: **Philosophy → Wundt (structuralism, 1879) → James (functionalism) → Behaviourism → Cognitive revolution → Modern psychology.**" },
          ],
          quiz: [
            { q: "Who is considered the founder of psychology as a science?", options: ["William James", "Wilhelm Wundt", "Sigmund Freud", "B.F. Skinner"], correct: 1 },
            { q: "What method did Wundt use to study conscious experience?", options: ["Brain scans", "Introspection", "Surveys", "Animal experiments"], correct: 1 },
            { q: "What did behaviourism focus on studying?", options: ["Unconscious desires", "Observable behaviour only", "Mental processes", "Brain structure"], correct: 1 },
            { type: "truefalse", q: "William James focused on the structure of consciousness, not its function.", correct: false, explain: "James focused on FUNCTION (how mental processes help adaptation), not structure — that was Wundt's focus." },
          ],
        },
        {
          id: "1.3",
          title: "Major Perspectives in Psychology",
          blocks: [
            { type: "p", text: "Modern psychology isn't one single approach — it's made up of multiple **perspectives** (ways of looking at behaviour and mental processes). Each perspective asks different questions and uses different methods. The best psychologists integrate multiple perspectives." },
            { type: "h", text: "Biological perspective" },
            { type: "p", text: "The **biological perspective** focuses on how bodily events and structures (genes, brain, nervous system, hormones) affect behaviour and mental processes. Example question: 'How do neurotransmitter imbalances contribute to depression?'" },
            { type: "h", text: "Behavioural perspective" },
            { type: "p", text: "The **behavioural perspective** focuses on how learning and environmental factors shape observable behaviour. Example question: 'How do rewards and punishments influence a child's behaviour?'" },
            { type: "h", text: "Cognitive perspective" },
            { type: "p", text: "The **cognitive perspective** focuses on mental processes like thinking, memory, problem-solving, and language. Example question: 'How do people make decisions under uncertainty?'" },
            { type: "h", text: "Psychodynamic perspective" },
            { type: "p", text: "The **psychodynamic perspective** (originating with Freud) focuses on unconscious drives, conflicts, and early childhood experiences. Example question: 'How do unconscious conflicts from childhood affect adult relationships?'" },
            { type: "h", text: "Humanistic perspective" },
            { type: "p", text: "The **humanistic perspective** (Rogers, Maslow) emphasises human potential, free will, and self-actualisation. Example question: 'What conditions help people reach their full potential?'" },
            { type: "h", text: "Sociocultural perspective" },
            { type: "p", text: "The **sociocultural perspective** focuses on how social and cultural factors influence behaviour. Example question: 'How do cultural norms affect emotional expression?'" },
            { type: "h", text: "Evolutionary perspective" },
            { type: "p", text: "The **evolutionary perspective** applies principles of natural selection to understand behaviour. Example question: 'Why do humans have a tendency to fear snakes more than cars?'" },
            { type: "h", text: "Biopsychosocial model" },
            { type: "p", text: "The **biopsychosocial model** integrates biological, psychological, and social factors — recognising that most behaviour is influenced by all three. This is the dominant approach in modern health psychology and medicine." },
            { type: "check", qtype: "multi", q: "Which of these are major perspectives in psychology?", options: ["Biological", "Behavioural", "Cognitive", "Astrological"], correct: [0, 1, 2], explain: "Biological, behavioural, and cognitive are all major perspectives. Astrological is not a psychological perspective." },
            { type: "callout", text: "Exam tip: **Know the 7 perspectives + biopsychosocial model.** Each asks different questions and emphasises different causes of behaviour." },
          ],
          quiz: [
            { q: "Which perspective focuses on unconscious drives and early childhood?", options: ["Cognitive", "Psychodynamic", "Behavioural", "Humanistic"], correct: 1 },
            { q: "Which perspective emphasises human potential and free will?", options: ["Biological", "Behavioural", "Humanistic", "Evolutionary"], correct: 2 },
            { q: "Which perspective applies natural selection to behaviour?", options: ["Sociocultural", "Evolutionary", "Cognitive", "Psychodynamic"], correct: 1 },
            { type: "type", q: "What model integrates biological, psychological, and social factors?", accepted: ["biopsychosocial", "biopsychosocial model"], explain: "The biopsychosocial model recognises that behaviour is influenced by all three types of factors." },
          ],
        },
        {
          id: "1.4",
          title: "Careers in Psychology",
          blocks: [
            { type: "p", text: "Psychology offers diverse career paths — from clinical practice to research to applied roles in business, education, and health. Most careers require graduate training beyond a bachelor's degree." },
            { type: "h", text: "Clinical psychologist" },
            { type: "p", text: "**Clinical psychologists** assess and treat mental, emotional, and behavioural disorders. They typically have a PhD or PsyD (doctoral degree), complete supervised clinical hours, and are licensed. They provide therapy and psychological testing, but cannot prescribe medication (in most places)." },
            { type: "h", text: "Counselling psychologist" },
            { type: "p", text: "**Counselling psychologists** help people with life adjustments, relationships, career decisions, and less severe mental health issues. Training is similar to clinical psychology but often focuses more on normal developmental issues." },
            { type: "h", text: "Research psychologist" },
            { type: "p", text: "**Research psychologists** work in universities, government, or private research institutions, conducting studies to advance psychological knowledge. They typically have PhDs and publish in academic journals." },
            { type: "h", text: "Industrial/organisational (I/O) psychologist" },
            { type: "p", text: "**I/O psychologists** apply psychology to workplace issues — employee selection, training, leadership, organisational culture, work-life balance. They work in corporations, consulting firms, or government." },
            { type: "h", text: "Forensic psychologist" },
            { type: "p", text: "**Forensic psychologists** work at the intersection of psychology and law — assessing competency, providing expert testimony, working with offenders, or consulting on jury selection." },
            { type: "h", text: "Educational psychologist" },
            { type: "p", text: "**Educational psychologists** study how people learn and develop in educational settings. They design interventions, assess learning disabilities, and work with schools to improve teaching methods." },
            { type: "h", text: "Health psychologist" },
            { type: "p", text: "**Health psychologists** study how psychological factors affect physical health — stress, coping with illness, health behaviours (smoking, exercise), and patient adherence to medical advice." },
            { type: "check", q: "Which career requires a medical degree (MD)?", options: ["Clinical psychologist", "Psychiatrist", "Counselling psychologist", "I/O psychologist"], correct: 1, explain: "Psychiatrists are medical doctors (MDs). Psychologists have PhD/PsyD degrees, not medical degrees." },
            { type: "callout", text: "Career reality check: **Most psychology careers require graduate school (master's or doctoral level).** A bachelor's alone qualifies you for limited roles." },
          ],
          quiz: [
            { q: "Which psychologist works with workplace issues?", options: ["Clinical", "Forensic", "Industrial/organisational", "Educational"], correct: 2 },
            { q: "Which psychologist works at the intersection of psychology and law?", options: ["Health", "Forensic", "Counselling", "Research"], correct: 1 },
            { q: "What degree do most clinical psychologists have?", options: ["Bachelor's", "Master's", "PhD or PsyD", "MD"], correct: 2 },
            { type: "truefalse", q: "Health psychologists study how psychological factors affect physical health.", correct: true, explain: "Yes — health psychologists focus on the mind-body connection in health and illness." },
          ],
        },
      ],
    },
    {
      id: "m2",
      number: 2,
      section: "Module 2",
      title: "Research Methods in Psychology",
      description: "How psychologists generate knowledge — scientific method, research designs, ethics, and statistics.",
      lessons: [
        {
          id: "2.1",
          title: "The Scientific Method in Psychology",
          blocks: [
            { type: "p", text: "Psychology is a science, which means it uses the **scientific method** — a systematic approach to asking and answering questions about the world. This is what separates psychology from pseudoscience and everyday intuition." },
            { type: "term", term: "Scientific method", definition: "A systematic approach to research involving observation, hypothesis formation, testing, and conclusion." },
            { type: "h", text: "Steps in the scientific method" },
            { type: "list", items: [
              "**1. Identify a research question**: What do you want to know? (e.g. 'Does sleep affect memory?')",
              "**2. Form a hypothesis**: A testable prediction (e.g. 'People who sleep 8 hours will remember more words than those who sleep 4 hours').",
              "**3. Design and conduct a study**: Choose appropriate methods to test your hypothesis.",
              "**4. Collect and analyse data**: Use statistical methods to examine your results.",
              "**5. Draw conclusions**: Do your results support your hypothesis? What are the limitations?",
              "**6. Share findings**: Publish in journals, present at conferences, allow others to replicate.",
            ]},
            { type: "h", text: "Hypotheses and theories" },
            { type: "p", text: "A **hypothesis** is a specific, testable prediction about what you expect to happen in your study. A **theory** is a broader explanation that integrates many findings and can generate multiple hypotheses. Theories are never 'proven' — they're supported or challenged by evidence." },
            { type: "term", term: "Hypothesis", definition: "A specific, testable prediction about the expected outcome of a study." },
            { type: "term", term: "Theory", definition: "A broad explanation that integrates many findings and generates testable hypotheses." },
            { type: "h", text: "Operational definitions" },
            { type: "p", text: "To make hypotheses testable, you need **operational definitions** — precise descriptions of how you'll measure your variables. For example, 'sleep' might be operationally defined as 'hours spent in bed monitored by actigraphy' and 'memory' as 'number of words recalled from a 20-word list'." },
            { type: "term", term: "Operational definition", definition: "A precise description of how a variable will be measured or manipulated in a study." },
            { type: "h", text: "Replication and reproducibility" },
            { type: "p", text: "**Replication** means repeating a study to see if you get the same results. This is crucial for building confidence in findings. Psychology is currently facing a **replication crisis** — many famous findings haven't replicated when other researchers tried. This has led to major reforms in how research is conducted." },
            { type: "term", term: "Replication", definition: "Repeating a study to verify that the original findings can be reproduced." },
            { type: "check", qtype: "truefalse", q: "Theories in psychology can be proven true with enough evidence.", correct: false, explain: "Theories are never 'proven' — they're supported or challenged by evidence, but always remain open to revision with new data." },
            { type: "callout", text: "Key principle: **Falsifiability** — a good hypothesis must be testable and potentially disprovable. If you can't imagine evidence that would contradict it, it's not scientific." },
          ],
          quiz: [
            { q: "What is a hypothesis?", options: ["A broad explanation of many findings", "A specific, testable prediction", "A proven fact", "An untestable belief"], correct: 1 },
            { q: "What is an operational definition?", options: ["A dictionary definition", "A precise description of how to measure a variable", "A research question", "A theory"], correct: 1 },
            { q: "Why is replication important?", options: ["It proves theories are true", "It verifies that findings can be reproduced", "It makes studies longer", "It's not important"], correct: 1 },
            { type: "type", q: "What crisis is psychology currently facing regarding study reproducibility?", accepted: ["replication crisis", "the replication crisis"], explain: "Psychology's replication crisis refers to many famous findings failing to replicate when other researchers tried." },
          ],
        },
        {
          id: "2.2",
          title: "Descriptive Research Methods",
          blocks: [
            { type: "p", text: "**Descriptive research** aims to create a snapshot of the current state of affairs — describing what's happening without manipulating variables or establishing cause-and-effect relationships. It's often the first step in exploring a new topic." },
            { type: "term", term: "Descriptive research", definition: "Research designed to provide a snapshot of the current state of affairs without manipulating variables." },
            { type: "h", text: "Naturalistic observation" },
            { type: "p", text: "In **naturalistic observation**, researchers observe behaviour in its natural setting without interfering. Example: Observing children's play behaviour on a playground. Strength: High ecological validity (real-world behaviour). Limitation: Cannot establish causation; observer bias possible." },
            { type: "term", term: "Naturalistic observation", definition: "Observing behaviour in its natural setting without interference from the researcher." },
            { type: "h", text: "Case studies" },
            { type: "p", text: "A **case study** is an in-depth examination of one individual, group, or situation. Famous example: Phineas Gage (railroad worker who survived a brain injury, revealing frontal lobe functions). Strength: Rich, detailed data. Limitation: Cannot generalise to broader populations." },
            { type: "term", term: "Case study", definition: "An in-depth examination of one individual, group, or situation." },
            { type: "h", text: "Surveys and interviews" },
            { type: "p", text: "**Surveys** use questionnaires to gather data from many participants about attitudes, beliefs, or behaviours. **Interviews** are more in-depth conversations. Strength: Can collect data from large samples efficiently. Limitation: Self-report biases (people may lie or misremember); sampling issues." },
            { type: "term", term: "Survey", definition: "A research method using questionnaires to gather data from many participants about attitudes, beliefs, or behaviours." },
            { type: "h", text: "Archival research" },
            { type: "p", text: "**Archival research** analyses existing records or data (e.g. historical documents, school records, social media posts). Strength: No need to collect new data; can examine long-term trends. Limitation: Data may be incomplete or biased; researcher has no control over original data quality." },
            { type: "check", q: "Which descriptive method provides the richest, most detailed data?", options: ["Survey", "Naturalistic observation", "Case study", "Archival research"], correct: 2, explain: "Case studies provide in-depth, detailed data about one individual or situation — richer than surveys or observations." },
            { type: "callout", text: "Key limitation of ALL descriptive methods: **They cannot establish cause-and-effect relationships.** Only experiments can do that." },
          ],
          quiz: [
            { q: "What is the main limitation of descriptive research?", options: ["It's too expensive", "It cannot establish cause-and-effect", "It takes too long", "It requires too many participants"], correct: 1 },
            { q: "Which method involves observing behaviour in its natural setting?", options: ["Case study", "Survey", "Naturalistic observation", "Archival research"], correct: 2 },
            { q: "What is a case study?", options: ["A survey of many people", "An in-depth examination of one individual or group", "A laboratory experiment", "A statistical analysis"], correct: 1 },
            { type: "truefalse", q: "Surveys can establish cause-and-effect relationships.", correct: false, explain: "Surveys are descriptive — they can show correlations but cannot prove causation. Only experiments can do that." },
          ],
        },
        {
          id: "2.3",
          title: "Correlational Research",
          blocks: [
            { type: "p", text: "**Correlational research** examines relationships between two or more variables without manipulating them. It tells you whether variables are related and how strongly — but crucially, **correlation does not equal causation**." },
            { type: "term", term: "Correlational research", definition: "Research designed to discover relationships among variables without manipulation." },
            { type: "h", text: "Correlation coefficient (r)" },
            { type: "p", text: "The **correlation coefficient (r)** is a number from -1 to +1 that describes the strength and direction of a relationship:" },
            { type: "list", items: [
              "**r = +1**: Perfect positive correlation (as one variable increases, the other always increases).",
              "**r = -1**: Perfect negative correlation (as one variable increases, the other always decreases).",
              "**r = 0**: No correlation (variables are unrelated).",
              "**r = +0.50**: Moderate positive correlation.",
              "**r = -0.30**: Weak negative correlation.",
            ]},
            { type: "term", term: "Correlation coefficient (r)", definition: "A number from -1 to +1 describing the strength and direction of a relationship between two variables." },
            { type: "h", text: "Positive and negative correlations" },
            { type: "list", items: [
              "**Positive correlation**: Both variables move in the same direction (e.g. study time and exam scores — more study → higher scores).",
              "**Negative correlation**: Variables move in opposite directions (e.g. stress and sleep quality — more stress → worse sleep).",
            ]},
            { type: "h", text: "Correlation ≠ causation" },
            { type: "p", text: "This is one of the most important principles in psychology. Just because two variables are correlated doesn't mean one causes the other. There are three possible explanations for any correlation:" },
            { type: "list", items: [
              "**A causes B** (e.g. smoking causes lung cancer).",
              "**B causes A** (e.g. lung cancer causes smoking — clearly wrong in this case, but possible in other correlations).",
              "**C causes both A and B** (third variable problem — e.g. ice cream sales and drowning are correlated, but both are caused by hot weather, not by each other).",
            ]},
            { type: "term", term: "Third variable problem", definition: "When a correlation between two variables is actually caused by a third, unmeasured variable affecting both." },
            { type: "check", qtype: "truefalse", q: "A correlation of -0.80 is stronger than a correlation of +0.50.", correct: true, explain: "Yes — the sign (+/-) only indicates direction. The absolute value (0.80 vs 0.50) indicates strength. -0.80 is a stronger relationship." },
            { type: "callout", text: "Golden rule: **Correlation does not equal causation.** Always ask: 'Could a third variable explain this? Could the direction be reversed?'" },
          ],
          quiz: [
            { q: "What does a correlation coefficient of +1 indicate?", options: ["No relationship", "Perfect positive correlation", "Perfect negative correlation", "Weak relationship"], correct: 1 },
            { q: "Which correlation is strongest?", options: ["+0.30", "-0.70", "+0.50", "-0.20"], correct: 1 },
            { q: "What does 'correlation does not equal causation' mean?", options: ["Correlations are always wrong", "Correlated variables may not have a causal relationship", "Causation is impossible to prove", "Correlations are stronger than causation"], correct: 1 },
            { type: "type", q: "What problem occurs when a third variable causes both correlated variables?", accepted: ["third variable problem", "third-variable problem", "confounding variable"], explain: "The third variable problem means the correlation may be spurious — caused by an unmeasured factor." },
          ],
        },
        {
          id: "2.4",
          title: "Experimental Research",
          blocks: [
            { type: "p", text: "**Experimental research** is the only method that can establish cause-and-effect relationships. In an experiment, the researcher manipulates one variable (the cause) and measures its effect on another variable, while controlling for other factors." },
            { type: "term", term: "Experimental research", definition: "Research in which the researcher manipulates one variable and measures its effect on another, allowing causal conclusions." },
            { type: "h", text: "Independent and dependent variables" },
            { type: "list", items: [
              "**Independent variable (IV)**: The variable the researcher manipulates (the 'cause'). Example: Amount of sleep (4 hours vs 8 hours).",
              "**Dependent variable (DV)**: The variable the researcher measures (the 'effect'). Example: Memory test score.",
            ]},
            { type: "term", term: "Independent variable (IV)", definition: "The variable that the researcher manipulates in an experiment." },
            { type: "term", term: "Dependent variable (DV)", definition: "The variable that the researcher measures in an experiment." },
            { type: "h", text: "Control groups and random assignment" },
            { type: "p", text: "To establish causation, you need:" },
            { type: "list", items: [
              "**Control group**: A group that doesn't receive the experimental manipulation (or receives a placebo), providing a baseline for comparison.",
              "**Random assignment**: Participants are randomly assigned to experimental or control groups, ensuring groups are equivalent at the start (any differences at the end are likely due to the manipulation).",
            ]},
            { type: "term", term: "Control group", definition: "A group in an experiment that doesn't receive the experimental manipulation, providing a baseline." },
            { type: "term", term: "Random assignment", definition: "Randomly assigning participants to experimental or control groups to ensure initial equivalence." },
            { type: "h", text: "Confounding variables" },
            { type: "p", text: "A **confounding variable** is an uncontrolled factor that might affect the results, making it unclear whether the IV or the confound caused changes in the DV. Good experiments control or eliminate confounds." },
            { type: "term", term: "Confounding variable", definition: "An uncontrolled factor that might affect results, making causal conclusions unclear." },
            { type: "h", text: "Internal vs external validity" },
            { type: "list", items: [
              "**Internal validity**: The extent to which you can confidently say the IV caused changes in the DV (high in well-controlled lab experiments).",
              "**External validity**: The extent to which findings generalise to real-world settings and populations (often lower in highly controlled lab studies).",
            ]},
            { type: "term", term: "Internal validity", definition: "The extent to which you can confidently conclude the IV caused changes in the DV." },
            { type: "term", term: "External validity", definition: "The extent to which findings generalise to real-world settings and populations." },
            { type: "check", q: "In an experiment testing whether caffeine improves memory, what is the independent variable?", options: ["Memory test score", "Amount of caffeine", "Number of participants", "Time of day"], correct: 1, explain: "The IV is what the researcher manipulates — in this case, the amount of caffeine given to participants." },
            { type: "callout", text: "Key advantage of experiments: **Only experiments can establish cause-and-effect.** Key trade-off: Higher internal validity often means lower external validity." },
          ],
          quiz: [
            { q: "What is the independent variable in an experiment?", options: ["The measured outcome", "The manipulated variable", "The control group", "The confounding factor"], correct: 1 },
            { q: "Why is random assignment important?", options: ["It makes experiments faster", "It ensures groups are equivalent at the start", "It increases external validity", "It's not important"], correct: 1 },
            { q: "What is a confounding variable?", options: ["The dependent variable", "The independent variable", "An uncontrolled factor affecting results", "The control group"], correct: 2 },
            { type: "truefalse", q: "Experiments have higher internal validity than correlational studies.", correct: true, explain: "Yes — experiments allow causal conclusions (high internal validity), while correlational studies do not." },
          ],
        },
        {
          id: "2.5",
          title: "Ethical Guidelines in Research",
          blocks: [
            { type: "p", text: "Psychological research involves human (and sometimes animal) participants, so strict ethical guidelines protect their welfare and rights. These guidelines were developed in response to historical abuses and are enforced by institutional review boards." },
            { type: "h", text: "Informed consent" },
            { type: "p", text: "**Informed consent** means participants must be told about the study's purpose, procedures, risks, and benefits, and must voluntarily agree to participate. They can withdraw at any time without penalty. Exceptions exist for certain observational studies where consent would make the research impossible." },
            { type: "term", term: "Informed consent", definition: "Participants must be informed about the study and voluntarily agree to participate." },
            { type: "h", text: "Deception and debriefing" },
            { type: "p", text: "Sometimes researchers must **deceive** participants (e.g. not revealing the true hypothesis) to get natural behaviour. This is only allowed when: (1) it's scientifically justified, (2) no alternative exists, and (3) risks are minimal. **Debriefing** afterward is mandatory — explaining the true purpose and why deception was necessary." },
            { type: "term", term: "Debriefing", definition: "Explaining the true purpose of a study to participants after their involvement, especially if deception was used." },
            { type: "h", text: "Confidentiality" },
            { type: "p", text: "Researchers must protect participants' **confidentiality** — keeping data private and anonymous whenever possible. Identifiable information should be stored securely and only accessible to the research team." },
            { type: "h", text: "Animal research ethics" },
            { type: "p", text: "Animal research is permitted only when: (1) it's scientifically valuable, (2) no alternative exists, (3) discomfort is minimised, and (4) it follows strict welfare guidelines. Many psychologists oppose or minimise animal research on ethical grounds." },
            { type: "h", text: "Institutional Review Boards (IRBs)" },
            { type: "p", text: "**IRBs** are committees that review all proposed research involving human participants to ensure it meets ethical standards. No study can begin without IRB approval." },
            { type: "term", term: "Institutional Review Board (IRB)", definition: "A committee that reviews research proposals to ensure they meet ethical standards." },
            { type: "check", qtype: "truefalse", q: "Researchers can deceive participants without any restrictions.", correct: false, explain: "Deception is only allowed when scientifically justified, no alternative exists, risks are minimal, and participants are debriefed afterward." },
            { type: "callout", text: "Ethical principle: **Beneficence** — research should maximise benefits and minimise harm to participants." },
          ],
          quiz: [
            { q: "What is informed consent?", options: ["Telling participants the results after the study", "Informing participants about the study and getting voluntary agreement", "Getting permission from the IRB", "Paying participants"], correct: 1 },
            { q: "When is deception allowed in research?", options: ["Never", "Only when scientifically justified and no alternative exists", "Always, if it's convenient", "Only with animals"], correct: 1 },
            { q: "What is an IRB?", options: ["A research method", "A committee that reviews research ethics", "A type of statistical test", "A psychological theory"], correct: 1 },
            { type: "type", q: "What must researchers do after using deception?", accepted: ["debrief", "debriefing", "debrief participants"], explain: "Debriefing explains the true purpose and why deception was necessary." },
          ],
        },
        {
          id: "2.6",
          title: "Basic Statistics for Psychology",
          blocks: [
            { type: "p", text: "Statistics are essential tools for making sense of psychological data. You don't need to be a mathematician, but you do need to understand basic concepts to interpret research findings." },
            { type: "h", text: "Descriptive statistics" },
            { type: "p", text: "**Descriptive statistics** summarise and describe data. Key measures:" },
            { type: "list", items: [
              "**Mean**: The average (sum of all scores divided by number of scores).",
              "**Median**: The middle score when all scores are ordered from lowest to highest.",
              "**Mode**: The most frequently occurring score.",
              "**Range**: The difference between the highest and lowest scores.",
              "**Standard deviation (SD)**: How spread out scores are from the mean (larger SD = more variability).",
            ]},
            { type: "term", term: "Mean", definition: "The average score — sum of all scores divided by the number of scores." },
            { type: "term", term: "Standard deviation (SD)", definition: "A measure of how spread out scores are from the mean." },
            { type: "h", text: "Inferential statistics" },
            { type: "p", text: "**Inferential statistics** help researchers decide whether their findings are likely to be real or just due to chance. Key concepts:" },
            { type: "list", items: [
              "**p-value**: The probability that results occurred by chance. **p < 0.05** means less than 5% probability — considered 'statistically significant' in psychology.",
              "**Statistical significance**: When p < 0.05, researchers conclude the effect is unlikely to be due to chance alone.",
            ]},
            { type: "term", term: "p-value", definition: "The probability that results occurred by chance. p < 0.05 is typically considered statistically significant." },
            { type: "h", text: "Type I and Type II errors" },
            { type: "list", items: [
              "**Type I error (false positive)**: Concluding there's an effect when there isn't one (rejecting a true null hypothesis).",
              "**Type II error (false negative)**: Concluding there's no effect when there actually is one (failing to reject a false null hypothesis).",
            ]},
            { type: "term", term: "Type I error", definition: "Concluding there's an effect when there isn't one (false positive)." },
            { type: "term", term: "Type II error", definition: "Concluding there's no effect when there actually is one (false negative)." },
            { type: "h", text: "Effect sizes" },
            { type: "p", text: "**Effect size** tells you how large an effect is, not just whether it's statistically significant. A tiny effect can be 'significant' with a huge sample, but might be meaningless in practice. Common effect size measures include Cohen's d and r." },
            { type: "term", term: "Effect size", definition: "A measure of the magnitude of an effect, independent of sample size." },
            { type: "check", q: "What does p < 0.05 mean?", options: ["There's a 95% chance the results are real", "There's less than 5% probability the results occurred by chance", "The effect is large", "The study is well-designed"], correct: 1, explain: "p < 0.05 means there's less than 5% probability the results occurred by chance — considered statistically significant." },
            { type: "callout", text: "Critical thinking: **Statistical significance ≠ practical importance.** A tiny effect can be 'significant' with a large enough sample." },
          ],
          quiz: [
            { q: "What is the mean?", options: ["The middle score", "The most frequent score", "The average score", "The highest score"], correct: 2 },
            { q: "What does a p-value less than 0.05 indicate?", options: ["The effect is large", "Results are statistically significant", "The study is flawed", "Results are not significant"], correct: 1 },
            { q: "What is a Type I error?", options: ["False negative", "False positive", "Correct conclusion", "Large effect"], correct: 1 },
            { type: "type", q: "What tells you the magnitude of an effect, not just whether it's significant?", accepted: ["effect size", "effect sizes"], explain: "Effect size measures how large an effect is, independent of statistical significance." },
          ],
        },
      ],
    },
