export const appliedNutritionReviews = {
  "1.1": [
    { q: "A meal provides carbohydrates, protein, fat, vitamins, and minerals. Which part of this list is mainly responsible for supplying calories?", options: ["Vitamins and minerals", "Carbohydrates, protein, and fat", "Minerals and water", "Vitamins and protein"], correct: 1, explain: "Carbohydrates, protein, and fat provide dietary energy, whereas vitamins and minerals support body processes without supplying calories." },
    { q: "True or false: A person can meet their macronutrient targets while still having a poor micronutrient intake.", type: "truefalse", correct: true, explain: "Macronutrient targets describe energy and building materials, but they do not guarantee adequate vitamins and minerals." },
    { q: "Which statements correctly describe fat-soluble vitamins?", type: "multi", options: ["Vitamins A, D, E, and K belong to this group", "They are stored in body fat or the liver", "They must all be consumed several times each day", "Excessive supplementation can create toxicity risk"], correct:, explain: "Fat-soluble vitamins are stored in the body, so they do not require the same frequent replacement as water-soluble vitamins and can accumulate." },[0][1][3]
    { q: "What is the name for nutrients needed in smaller amounts that include vitamins and minerals?", type: "type", accepted: ["micronutrients", "micro nutrients"], explain: "Micronutrients are vitamins and minerals required in relatively small quantities for processes such as enzyme activity and cellular signalling." }
  ],
  "1.2": [
    { q: "Two foods each contain 300 kcal, but one is rich in protein and fibre while the other is mostly refined sugar; which difference is most directly expected?", options: ["The foods contain different amounts of energy by definition", "The protein-and-fibre food may produce greater satiety", "The sugary food must contain more vitamins", "The protein-and-fibre food cannot affect body weight"], correct: 1, explain: "Calories quantify energy, but protein and fibre can influence fullness and therefore eating behaviour differently from refined sugar." },
    { q: "True or false: The thermic effect of food means that the body uses some energy to digest and process what is eaten.", type: "truefalse", correct: true, explain: "The thermic effect of food is the energy expended during digestion, absorption, and processing of nutrients." },
    { q: "Which factors can make two equal-calorie foods have different physiological effects?", type: "multi", options: ["Protein and fibre content", "Hormonal response", "Nutrient density", "The fact that both contain calories"], correct:, explain: "Protein, fibre, nutrient density, and hormonal effects differ between foods even when their energy content is equal." },[0][1][2]
    { q: "Which macronutrient generally has the greatest thermic effect of food?", type: "type", accepted: ["protein"], explain: "Protein typically requires the greatest proportion of its energy to be used for digestion and processing." }
  ],
  "1.3": [
    { q: "A recommendation designed around the needs of an average population rather than a particular person's response best reflects which nutrition lens?", options: ["Naturopathic bio-individuality", "Mainstream population-level nutrition", "Traditional food-as-medicine practice", "An elimination-diet protocol"], correct: 1, explain: "Mainstream nutrition commonly develops guidelines from population data intended to apply broadly rather than perfectly fit each individual." },
    { q: "True or false: The two paradigms may disagree about calorie counting while still agreeing that eating more vegetables is generally beneficial.", type: "truefalse", correct: true, explain: "The lesson presents vegetable intake as common ground while identifying calorie emphasis as an area of disagreement." },
    { q: "Which ideas are characteristic of the naturopathic lens?", type: "multi", options: ["Whole-food emphasis", "Bio-individuality", "Food synergy", "Exclusive reliance on population averages"], correct:, explain: "Naturopathic nutrition emphasizes whole foods, individual variation, and interactions among food components rather than relying only on population averages." },[0][1][2]
    { q: "What term describes the idea that the same diet may affect different people differently?", type: "type", accepted: ["bio-individuality", "bio individuality", "individuality"], explain: "Bio-individuality refers to variation in nutritional responses and needs between people." }
  ],
  "1.4": [
    { q: "A supplement company funds a small study of its own product and reports a positive result; what is the most appropriate first response?", options: ["Accept the claim because the study is recent", "Examine funding, methods, sample size, and whether independent studies agree", "Reject every result from the company automatically", "Treat the testimonial as stronger evidence"], correct: 1, explain: "Funding and study limitations do not prove a result false, but they make critical appraisal and independent replication especially important." },
    { q: "True or false: An observational association can be useful for generating a hypothesis but does not by itself establish that one factor caused another.", type: "truefalse", correct: true, explain: "Observational studies can identify relationships, but confounding and other biases prevent them from proving causation on their own." },
    { q: "Which features make a nutrition claim more trustworthy?", type: "multi", options: ["A clearly described study design", "Results consistent with multiple independent studies", "Transparent funding and conflicts of interest", "A dramatic headline with no citation"], correct:, explain: "Transparent methods, independent consistency, and disclosed funding improve confidence, whereas unsupported headlines do not." },[0][1][2]
    { q: "What is the term for a study result being reproduced by other researchers?", type: "type", accepted: ["replication", "replicated evidence"], explain: "Replication means independent researchers obtain compatible findings, increasing confidence that an observed result is not a chance finding." }
  ],
  "1.5": [
    { q: "Why might a dietary guideline fail to represent the ideal intake for a particular athlete?", options: ["Guidelines are usually based on population averages and minimum requirements", "Athletes cannot absorb nutrients", "Guidelines never use scientific evidence", "Athletes do not need micronutrients"], correct: 0, explain: "Population guidelines are broad reference points and may not reflect the higher or different needs created by training and individual circumstances." },
    { q: "True or false: Public comment is one stage through which draft nutrition recommendations may be reviewed before final publication.", type: "truefalse", correct: true, explain: "Guideline processes can include public and stakeholder feedback before recommendations are finalised." },
    { q: "Which factors can complicate the process of making nutrition guidelines?", type: "multi", options: ["Industry influence", "Limitations of observational evidence", "Differences between individuals", "The fact that guidelines are always updated immediately"], correct:, explain: "Industry influence, imperfect evidence, and one-size-fits-all limitations can all affect guideline development and interpretation." },[0][1][2]
    { q: "What does the abbreviation AMDR stand for?", type: "type", accepted: ["acceptable macronutrient distribution range", "acceptable macronutrient distribution ranges"], explain: "AMDR refers to the suggested percentage ranges of energy contributed by carbohydrate, protein, and fat." }
  ],
  "1.6": [
    { q: "Which conclusion best integrates the module's treatment of calories and food quality?", options: ["Calories are irrelevant if food is minimally processed", "Calories matter for energy balance, but they do not capture every health-relevant property of food", "Only micronutrients determine body weight", "All equal-calorie foods produce identical outcomes"], correct: 1, explain: "Energy intake remains relevant to weight, while nutrient density, satiety, processing, and metabolic effects add important context." },
    { q: "True or false: A systematic review or meta-analysis generally provides a stronger basis for a broad nutrition conclusion than one isolated study.", type: "truefalse", correct: true, explain: "Synthesising multiple studies can provide more reliable evidence than relying on a single potentially unusual or limited result." },
    { q: "Which statements accurately combine the module's main concepts?", type: "multi", options: ["Protein has a relatively high thermic effect", "RDA values are generally intended to prevent deficiency rather than maximise performance", "Naturopathic nutrition emphasizes bio-individuality", "Micronutrients are the main source of dietary calories"], correct:, explain: "The module distinguishes protein's high thermic effect, RDAs as population minimums, and bio-individuality as a naturopathic principle." },[0][1][2]
    { q: "What is the abbreviation for Recommended Dietary Allowance?", type: "type", accepted: ["RDA", "recommended dietary allowance"], explain: "RDA stands for Recommended Dietary Allowance, a population reference intended to cover basic requirements for most people." }
  ],
  "2.1": [
    { q: "A patient has adequate calories but inadequate protein; which process is most directly threatened over time?", options: ["The body's ability to synthesise and replace functional proteins", "The storage of vitamins in fat", "The production of dietary fibre", "The conversion of water into minerals"], correct: 0, explain: "Protein is continuously turned over and is needed to build enzymes, antibodies, structural tissues, hormones, and transport proteins." },
    { q: "True or false: Protein can serve as an energy source, but this is not its only or primary structural role in the body.", type: "truefalse", correct: true, explain: "Protein can provide energy when needed, but it also performs essential structural, enzymatic, hormonal, immune, and transport functions." },
    { q: "Which are protein-based roles or structures?", type: "multi", options: ["Antibodies", "Collagen", "Haemoglobin", "Glycogen storage"], correct:, explain: "Antibodies, collagen, and haemoglobin are proteins, whereas glycogen is a carbohydrate storage form." },[0][1][2]
    { q: "What is the process of continually breaking down old proteins and building new ones called?", type: "type", accepted: ["protein turnover", "turnover"], explain: "Protein turnover describes the ongoing balance between protein breakdown and protein synthesis." }
  ],
  "2.2": [
    { q: "A vegan meal pattern relies on rice, beans, tofu, and nuts across the day; why can variety help compensate for limitations in individual plant proteins?", options: ["Different foods can contribute complementary essential amino acids", "Plant proteins automatically become animal proteins", "Variety removes all calories from the meals", "Every plant food contains identical amino acids"], correct: 0, explain: "Different plant foods may be low in different essential amino acids, so combining varied sources across the day can improve the overall amino-acid pattern." },
    { q: "True or false: A food being plant-based automatically means that its protein is incomplete.", type: "truefalse", correct: false, explain: "Some plant foods, including soy and quinoa, can provide all nine essential amino acids in adequate proportions." },
    { q: "Which statements are accurate about plant protein sources?", type: "multi", options: ["Soy can provide a complete protein profile", "Cooking or fermenting can reduce some anti-nutrients", "Plant foods can also contribute fibre and phytonutrients", "All plant proteins have identical digestibility to whey"], correct:, explain: "Soy is a complete plant protein, processing can improve tolerance or digestibility, and plant foods offer benefits beyond protein." },[0][1][2]
    { q: "What is the term for combining foods whose amino-acid limitations complement one another?", type: "type", accepted: ["protein complementation", "complementary proteins", "complementing proteins"], explain: "Protein complementation combines different sources to create a more complete overall essential-amino-acid pattern." }
  ],
  "2.3": [
    { q: "A sedentary adult and a strength athlete weigh the same; why might their protein targets differ?", options: ["Protein recommendations can change with training demands and muscle-building goals", "The athlete cannot use dietary protein", "The sedentary adult needs protein only once per week", "Body weight has no relationship to protein needs"], correct: 0, explain: "Protein needs are commonly expressed relative to body weight but also vary with activity, training, age, and goals." },
    { q: "True or false: The protein RDA should automatically be treated as the optimal target for maximising muscle growth.", type: "truefalse", correct: false, explain: "The RDA is designed as a minimum to prevent deficiency and is not necessarily optimal for muscle gain or athletic performance." },
    { q: "Which circumstances can justify considering protein intake above the sedentary-adult RDA?", type: "multi", options: ["Resistance training", "Calorie-restricted weight loss", "Older age with anabolic resistance", "Having no nutritional goal at all"], correct:, explain: "Training, energy restriction, and older age can all increase the value of a higher protein intake." },[0][1][2]
    { q: "What unit is commonly used to express protein targets relative to body size?", type: "type", accepted: ["grams per kilogram", "g/kg", "g per kg", "grams per kg body weight"], explain: "Protein recommendations are often expressed as grams of protein per kilogram of body weight per day." }
  ],
  "2.4": [
    { q: "Why might a person need a larger serving of a plant protein than whey to reach a similar leucine trigger?", options: ["Many plant proteins contain less leucine per gram", "Leucine exists only in animal foods", "Whey contains no amino acids", "Plant protein always contains more fat"], correct: 0, explain: "Many plant proteins are less leucine-dense, so a larger serving or blended source may be needed to reach a comparable leucine amount." },
    { q: "True or false: PDCAAS and DIAAS are measures intended to assess protein quality rather than total calorie content.", type: "truefalse", correct: true, explain: "These scoring systems consider amino-acid adequacy and digestibility to evaluate protein quality." },
    { q: "Which factors can reduce the effective digestibility or quality assessment of some plant proteins?", type: "multi", options: ["Phytates", "Lectins", "Tannins", "Leucine itself"], correct:, explain: "Phytates, lectins, and tannins are anti-nutrients that can interfere with digestion or nutrient availability, whereas leucine supports muscle protein synthesis." },[0][1][2]
    { q: "Which amino acid acts as a key signal for initiating muscle protein synthesis through mTOR?", type: "type", accepted: ["leucine", "L-leucine"], explain: "Leucine is the principal amino-acid signal that activates mTOR-related muscle protein synthesis." }
  ],
  "2.5": [
    { q: "Which meal pattern best reflects the module's overall protein guidance for an active adult?", options: ["Only one very large protein meal each week", "Regular varied protein servings with attention to total daily intake and quality", "Avoiding plant proteins entirely", "Using supplements regardless of food intake"], correct: 1, explain: "The module emphasises sufficient daily protein, varied sources, protein quality, and distribution rather than a single rigid source or supplement requirement." },
    { q: "True or false: Protein quality involves more than simply counting grams on a nutrition label.", type: "truefalse", correct: true, explain: "Amino-acid profile, leucine content, digestibility, and bioavailability all affect the practical quality of a protein source." },
    { q: "Which statements are supported by the module?", type: "multi", options: ["The body cannot meaningfully store excess protein as a dedicated reserve", "Quinoa is among the complete plant proteins", "Older adults may benefit from higher protein intake", "The RDA is a muscle-gain prescription for athletes"], correct:, explain: "Protein storage is limited, quinoa is a complete plant protein, and older adults may need more, while the RDA is not an athlete-specific muscle-gain prescription." },[0][1][2]
    { q: "What is the name of the amino acid most associated with triggering muscle protein synthesis?", type: "type", accepted: ["leucine", "L-leucine"], explain: "Leucine is the key amino-acid signal for stimulating muscle protein synthesis." }
  ],
  "3.1": [
    { q: "A bowl contains the same carbohydrate food in two portions; which measure changes when the serving size changes while the food's GI remains the same?", options: ["Glycemic load", "The food's carbohydrate identity", "Whether glucose is a monosaccharide", "The number of sugar units in each molecule"], correct: 0, explain: "Glycemic load incorporates both a food's GI and the amount of carbohydrate consumed in the serving." },
    { q: "True or false: A carbohydrate's classification as complex is not enough by itself to predict that it will have a low glycemic response.", type: "truefalse", correct: true, explain: "Processing, cooking, food structure, ripeness, and meal composition can make some complex carbohydrates raise blood glucose rapidly." },
    { q: "Which factors can influence a meal's glycemic response?", type: "multi", options: ["Fibre content", "Cooking and processing", "The presence of protein or fat", "Whether the food is labelled organic"], correct:, explain: "Fibre, preparation, processing, and accompanying macronutrients can alter how quickly carbohydrate is digested and absorbed." },[0][1][2]
    { q: "What is the abbreviation for glycemic load?", type: "type", accepted: ["GL", "glycemic load"], explain: "GL stands for glycemic load, which combines glycemic index with the carbohydrate amount in a serving." }
  ],
  "3.2": [
    { q: "Why is replacing one fat with another important when interpreting saturated-fat research?", options: ["The replacement nutrient can influence the resulting lipid and disease risk", "All fats have identical metabolic effects", "Replacement removes all calories from the diet", "Saturated fat is never absorbed"], correct: 0, explain: "The health effect of reducing saturated fat depends partly on whether it is replaced with unsaturated fat, refined carbohydrate, or another nutrient." },
    { q: "True or false: Artificial trans fats from partially hydrogenated oils are treated differently from naturally occurring fats in the lesson's recommendations.", type: "truefalse", correct: true, explain: "The lesson identifies industrial trans fats as particularly harmful and recommends avoiding them." },
    { q: "Which foods are generally sources of unsaturated fats emphasised in the lesson?", type: "multi", options: ["Olive oil", "Avocado", "Fatty fish", "Partially hydrogenated shortening"], correct:, explain: "Olive oil, avocado, and fatty fish provide predominantly unsaturated fats, whereas partially hydrogenated shortening is a source of industrial trans fats." },[0][1][2]
    { q: "What is the abbreviation for monounsaturated fat?", type: "type", accepted: ["MUFA", "monounsaturated fatty acid", "monounsaturated fat"], explain: "MUFA is the standard abbreviation for monounsaturated fatty acid or fat." }
  ],
  "3.3": [
    { q: "Why is the claim that seed oils are simply either 'toxic' or 'heart-healthy' an oversimplification?", options: ["Evidence depends on amount, cooking, replacement food, and overall dietary context", "Seed oils contain no energy", "All studies agree completely", "Their fatty-acid composition never matters"], correct: 0, explain: "Seed-oil effects depend on dose, food context, processing, heating, and what nutrient they replace, so an absolute label is misleading." },
    { q: "True or false: A food's high omega-6 content alone proves that consuming any amount of it will cause disease.", type: "truefalse", correct: false, explain: "High omega-6 content may be relevant to dietary patterns, but it does not by itself prove that every amount causes disease." },
    { q: "Which points are relevant when evaluating seed-oil claims?", type: "multi", options: ["Whether the oil is repeatedly heated", "What food or fat it replaces", "The total dietary pattern", "Whether every seed oil has exactly the same composition"], correct:, explain: "Heating, replacement, and overall dietary context matter, while seed oils differ and should not all be treated as chemically identical." },[0][1][2]
    { q: "What is the principal omega-6 fatty acid commonly discussed in seed oils?", type: "type", accepted: ["linoleic acid", "LA"], explain: "Linoleic acid is the major omega-6 fatty acid in many common seed oils." }
  ],
  "3.4": [
    { q: "Why can resistant starch behave physiologically more like fibre than like rapidly digested starch?", options: ["It resists digestion in the small intestine and can be fermented by gut microbes", "It contains no carbohydrates", "It is absorbed directly as fat", "It is always insoluble in water"], correct: 0, explain: "Resistant starch escapes much small-intestinal digestion and can reach the colon, where microbes ferment it." },
    { q: "True or false: Increasing fibre intake very rapidly can cause gastrointestinal discomfort even when fibre is generally beneficial.", type: "truefalse", correct: true, explain: "A sudden increase in fibre can produce gas or bloating, so gradual increases and adequate fluid are often better tolerated." },
    { q: "Which outcomes are associated with fermentable dietary fibre?", type: "multi", options: ["Production of short-chain fatty acids", "Support for beneficial gut bacteria", "Improved satiety", "Guaranteed elimination of all digestive symptoms"], correct:, explain: "Fermentable fibre can feed gut microbes, produce short-chain fatty acids, and contribute to fullness, but it cannot guarantee symptom elimination." },[0][1][2]
    { q: "What short-chain fatty acid is especially important as fuel for colon cells?", type: "type", accepted: ["butyrate", "butyric acid"], explain: "Butyrate is a short-chain fatty acid produced by microbial fermentation and is an important fuel for colon cells." }
  ],
  "3.5": [
    { q: "Which comparison best captures the difference between GI and GL?", options: ["GI describes a food's relative glucose-raising speed, while GL also accounts for the amount eaten", "GI measures fat and GL measures protein", "GI applies only to supplements and GL only to fruit", "They are identical measurements"], correct: 0, explain: "Glycemic load adds serving-related carbohydrate quantity to the glycemic-index concept." },
    { q: "True or false: The course's discussion supports avoiding industrial trans fats more strongly than treating every saturated fat as identical.", type: "truefalse", correct: true, explain: "The lesson identifies industrial trans fats as unequivocally harmful while presenting saturated-fat effects as context-dependent." },
    { q: "Which claims are consistent with the module review?", type: "multi", options: ["Soluble fibre can form a gel", "Heating unstable oils can promote oxidation", "Meal composition can affect glycemic response", "All complex carbohydrates have low GI"], correct:, explain: "Soluble fibre, oil oxidation, and meal composition are covered concepts, while carbohydrate complexity alone does not guarantee a low GI." },[0][1][2]
    { q: "What term describes the amount of carbohydrate in a serving multiplied by its glycemic effect?", type: "type", accepted: ["glycemic load", "GL"], explain: "Glycemic load incorporates both glycemic index and the carbohydrate quantity in the portion consumed." }
  ],
  "4.1": [
    { q: "Why can taking a high dose of a fat-soluble vitamin be riskier than obtaining the same vitamin from ordinary food?", options: ["Fat-soluble vitamins can accumulate in body tissues", "Food contains no vitamins", "Water-soluble vitamins are stored more extensively", "Fat-soluble vitamins provide calories"], correct: 0, explain: "Fat-soluble vitamins are stored in body fat and the liver, so excessive supplemental intake can build up over time." },
    { q: "True or false: Water-soluble vitamins are impossible to overdose on under all circumstances.", type: "truefalse", correct: false, explain: "Although excess is often excreted, high-dose supplements of water-soluble vitamins can still cause adverse effects." },
    { q: "Which vitamin-to-function pairings are correct?", type: "multi", options: ["Vitamin A — vision and immune function", "Vitamin K — blood clotting", "Vitamin C — collagen synthesis", "Vitamin D — primary calorie production"], correct:, explain: "Vitamins A, K, and C support vision and immunity, clotting, and collagen synthesis respectively, while vitamin D does not produce calories." },[0][1][2]
    { q: "Which four-letter sequence identifies the fat-soluble vitamins?", type: "type", accepted: ["ADEK", "A, D, E, K", "A D E K"], explain: "The fat-soluble vitamins are A, D, E, and K, commonly remembered as ADEK." }
  ],
  "4.2": [
    { q: "A person has fatigue, pale skin, and shortness of breath; which mineral deficiency would be especially important to investigate?", options: ["Iron", "Iodine", "Zinc", "Calcium"], correct: 0, explain: "Iron deficiency can impair haemoglobin production and oxygen transport, producing fatigue, pallor, and breathlessness." },
    { q: "True or false: Taking iron supplements without confirming deficiency is always harmless.", type: "truefalse", correct: false, explain: "Excess iron can be harmful, so supplementation should generally be guided by appropriate testing and clinical advice." },
    { q: "Which mineral-function pairings are accurate?", type: "multi", options: ["Magnesium — many enzyme reactions", "Zinc — immune function and wound healing", "Iron — oxygen transport", "Iodine — muscle glycogen storage"], correct:, explain: "Magnesium, zinc, and iron support the listed functions, whereas iodine is primarily needed for thyroid hormone production." },[0][1][2]
    { q: "Which mineral is the central nutrient in haemoglobin's oxygen-carrying function?", type: "type", accepted: ["iron", "Fe"], explain: "Iron in haemoglobin enables red blood cells to bind and transport oxygen." }
  ],
  "4.3": [
    { q: "Why might a clinician order methylmalonic acid or homocysteine when B12 status is uncertain?", options: ["Serum B12 alone may not accurately reflect functional deficiency", "Those tests measure hydration only", "B12 is stored exclusively in muscle", "They directly measure dietary fibre"], correct: 0, explain: "Functional markers such as methylmalonic acid and homocysteine can reveal impaired B12-dependent metabolism when serum B12 is ambiguous." },
    { q: "True or false: Symptoms such as fatigue are specific enough by themselves to identify one particular nutrient deficiency.", type: "truefalse", correct: false, explain: "Fatigue and similar symptoms have many possible causes, so deficiency diagnosis requires context and appropriate testing." },
    { q: "Which groups are at increased risk of particular deficiencies described in the lesson?", type: "multi", options: ["Vegans may be at risk of B12 deficiency", "People with limited sun exposure may be at risk of vitamin D deficiency", "People with substantial menstrual blood loss may be at risk of iron deficiency", "Everyone with fatigue necessarily has magnesium deficiency"], correct:, explain: "Dietary pattern, sun exposure, and blood loss can raise risk, but symptoms alone do not establish a magnesium deficiency." },[0][1][2]
    { q: "What blood marker is commonly used to assess stored iron?", type: "type", accepted: ["ferritin", "serum ferritin"], explain: "Ferritin generally reflects the body's iron stores, although inflammation and other factors can affect interpretation." }
  ],
  "4.4": [
    { q: "Why is food-first advice not necessarily the same as saying supplements are never useful?", options: ["Supplements can help correct diagnosed deficiencies or address specific needs", "Whole foods contain no measurable nutrients", "Supplements always replace meals", "Food cannot provide minerals"], correct: 0, explain: "Food is generally the foundation, while targeted supplementation can be appropriate for diagnosed deficiencies, life stages, or dietary restrictions." },
    { q: "True or false: A supplement's presence in a product does not automatically prove that it is needed or beneficial for every person.", type: "truefalse", correct: true, explain: "Supplement decisions depend on nutritional status, diet, health conditions, dose, and evidence rather than marketing alone." },
    { q: "Which situations may justify targeted supplementation?", type: "multi", options: ["A confirmed deficiency", "A dietary restriction that makes a nutrient difficult to obtain", "A life stage with increased needs", "Replacing all meals with pills despite an adequate diet"], correct:, explain: "Deficiency, restricted diets, and life stages can create legitimate reasons for targeted supplements, whereas pills are not a substitute for a balanced diet." },[0][1][2]
    { q: "Which vitamin is commonly paired with iron-rich plant foods to improve non-haem iron absorption?", type: "type", accepted: ["vitamin C", "C", "ascorbic acid"], explain: "Vitamin C can enhance absorption of non-haem iron from plant foods." }
  ],
  "4.5": [
    { q: "Which strategy best reflects the module's approach to suspected micronutrient deficiency?", options: ["Use symptoms alone to choose several high-dose supplements", "Combine dietary assessment with appropriate testing and targeted treatment", "Avoid all foods containing the suspected nutrient", "Assume a multivitamin resolves every deficiency"], correct: 1, explain: "Assessment and testing help distinguish possible deficiencies and support safer, more targeted interventions." },
    { q: "True or false: Fat-soluble vitamins and iron deserve particular caution because excessive supplemental intake can be harmful.", type: "truefalse", correct: true, explain: "Fat-soluble vitamins can accumulate, and excess iron can cause toxicity, so both should be supplemented carefully." },
    { q: "Which statements accurately summarise the module?", type: "multi", options: ["Magnesium participates in hundreds of enzyme reactions", "Ferritin is useful for assessing iron stores", "Serum B12 can be misleading in isolation", "Whole foods are always pharmacologically stronger than any supplement"], correct:, explain: "The module covers magnesium's broad role, ferritin for iron stores, and the limitations of serum B12, but does not claim that food is always pharmacologically stronger." },[0][1][2]
    { q: "What is the name of the vitamin commonly called cobalamin?", type: "type", accepted: ["vitamin B12", "B12", "cobalamin"], explain: "Cobalamin is the chemical name for vitamin B12, which is important for blood and nervous-system function." }
  ],
  "5.1": [
    { q: "Why is a fixed 'eight glasses' rule an incomplete hydration prescription?", options: ["Water needs vary with body size, activity, climate, diet, and health", "Adults do not need water", "All beverages are dehydrating", "Urine colour never changes"], correct: 0, explain: "Hydration requirements differ substantially between people and situations, so a single fixed volume cannot fit everyone." },
    { q: "True or false: Food moisture and non-caffeinated beverages can contribute to total daily water intake.", type: "truefalse", correct: true, explain: "Total water intake includes water in foods and drinks, not just plain water." },
    { q: "Which situations generally increase fluid requirements?", type: "multi", options: ["Prolonged intense exercise", "Hot or humid conditions", "Fever, vomiting, or diarrhoea", "Severe fluid-restricted kidney or heart disease without clinician guidance"], correct:, explain: "Exercise, heat, and fluid losses increase needs, whereas some kidney or heart conditions may require prescribed restriction." },[0][1][2]
    { q: "What urine colour is commonly used as a rough sign of adequate hydration?", type: "type", accepted: ["pale yellow", "light yellow"], explain: "Pale-yellow urine is a practical, though imperfect, indicator that hydration is generally adequate." }
  ],
  "5.2": [
    { q: "Why can drinking excessive plain water during prolonged exercise be dangerous?", options: ["It can dilute blood sodium and contribute to hyponatraemia", "It always raises blood sodium", "It prevents all sweating", "It converts sodium into protein"], correct: 0, explain: "Excessive hypotonic fluid intake can dilute serum sodium, especially when substantial sodium is lost through sweating." },
    { q: "True or false: Sodium is the main electrolyte lost in sweat for many people during prolonged exercise.", type: "truefalse", correct: true, explain: "Sweat commonly contains substantial sodium, making sodium replacement particularly relevant during prolonged or heavy sweating." },
    { q: "When might an electrolyte drink be more useful than plain water?", type: "multi", options: ["Long, intense exercise with heavy sweating", "Repeated vomiting or diarrhoea", "Extended heat exposure", "A short sedentary period in a cool room for every person"], correct:, explain: "Prolonged sweat or gastrointestinal losses can remove electrolytes as well as water, while routine sedentary hydration usually does not require a specialised drink." },[0][1][2]
    { q: "What is the medical term for abnormally low blood sodium?", type: "type", accepted: ["hyponatraemia", "hyponatremia", "low sodium"], explain: "Hyponatraemia, also spelled hyponatremia, means that blood sodium concentration is abnormally low." }
  ],
  "5.3": [
    { q: "Why might constipation occur during chronic under-hydration?", options: ["The colon can absorb more water from stool, making it harder", "Water automatically increases stool hardness", "Dehydration creates dietary fibre", "The kidneys stop producing all urine"], correct: 0, explain: "When the body is short on fluid, more water may be reclaimed from the colon, leaving stool drier and harder." },
    { q: "True or false: Mild dehydration can affect concentration and physical performance before severe thirst develops.", type: "truefalse", correct: true, explain: "Cognitive and exercise effects can appear with relatively modest fluid loss, while thirst may lag behind physiological need." },
    { q: "Which symptoms may be associated with under-hydration?", type: "multi", options: ["Headache", "Brain fog", "Constipation", "Consistently improved endurance"], correct:, explain: "Headache, impaired concentration, and constipation are recognised possible effects of inadequate hydration, whereas endurance generally worsens." },[0][1][2]
    { q: "What simple field test involves pinching the skin and observing how quickly it returns?", type: "type", accepted: ["skin turgor test", "skin turgor"], explain: "The skin-turgor test uses the speed of skin recoil as a rough, imperfect indicator of hydration status." }
  ],
  "5.4": [
    { q: "Which hydration plan best reflects the module's overall approach?", options: ["Use one fixed daily volume regardless of conditions", "Adjust intake to context and monitor practical signs such as urine colour and body-weight changes", "Drink as much plain water as possible during every workout", "Ignore symptoms unless urine is completely clear"], correct: 1, explain: "Hydration should be individualised to activity, climate, health, and fluid losses while using practical indicators rather than a rigid rule." },
    { q: "True or false: Electrolyte replacement may matter when fluid losses occur through sweat, vomiting, or diarrhoea rather than through ordinary daily activity.", type: "truefalse", correct: true, explain: "These situations can remove sodium and other electrolytes along with water, making plain water alone insufficient in some cases." },
    { q: "Which statements fit the module's guidance?", type: "multi", options: ["Pale-yellow urine is a useful rough indicator", "One kilogram of exercise-related weight loss approximates one litre of fluid loss", "Thirst is not always an early signal", "Clear urine is always the ideal target"], correct:, explain: "Urine colour, exercise weight change, and the lagging nature of thirst are useful concepts, while perfectly clear urine is not universally the goal." },[0][1][2]
    { q: "What is the main electrolyte concern when someone drinks excessive plain water during heavy exertion?", type: "type", accepted: ["hyponatraemia", "hyponatremia", "low blood sodium"], explain: "Excessive hypotonic fluid intake can dilute blood sodium and cause hyponatraemia." }
  ],
  "6.1": [
    { q: "During a maximal effort lasting only a few seconds, why can creatine supplementation help?", options: ["Phosphocreatine helps rapidly regenerate ATP", "It supplies all energy through fat oxidation", "It prevents carbohydrate digestion", "It directly increases oxygen concentration in the lungs"], correct: 0, explain: "The phosphocreatine system donates phosphate to ADP, rapidly regenerating ATP for short, high-intensity efforts." },
    { q: "True or false: Creatine's initial weight increase, when it occurs, is mainly associated with water stored inside muscle rather than fat gain.", type: "truefalse", correct: true, explain: "Creatine increases intramuscular water in many users, which is distinct from accumulating body fat." },
    { q: "Which outcomes have evidence or active research support in the lesson?", type: "multi", options: ["Improved strength and power", "Increased lean mass with training", "Possible cognitive benefits in some settings", "Guaranteed improvement in long-duration endurance"], correct:, explain: "Creatine is well supported for high-intensity performance and muscle gain, with emerging cognitive evidence, but is not a guaranteed endurance aid." },[0][1][2]
    { q: "What is the energy-rich compound stored in muscle that creatine helps replenish?", type: "type", accepted: ["phosphocreatine", "phosphocreatine (PCr)", "PCr"], explain: "Creatine is stored partly as phosphocreatine, which supports rapid ATP regeneration." }
  ],
  "6.2": [
    { q: "Why might a vegetarian show a larger response to creatine supplementation than a meat eater?", options: ["Vegetarians may begin with lower dietary creatine stores", "Vegetarians cannot produce ATP", "Meat eaters cannot absorb creatine", "Creatine only works without exercise"], correct: 0, explain: "Lower baseline creatine intake and stores can leave more room for supplementation to produce a relative change." },
    { q: "True or false: The strongest established creatine applications in the lesson concern repeated high-intensity efforts rather than purely long-duration endurance.", type: "truefalse", correct: true, explain: "Creatine supports the ATP-phosphocreatine system and is most consistently useful for strength, power, and repeated intense efforts." },
    { q: "Which groups are identified as potentially benefiting from creatine beyond young strength athletes?", type: "multi", options: ["Older adults", "Vegetarians or vegans", "People dieting while trying to preserve lean mass", "People seeking guaranteed treatment for neurological disease"], correct:, explain: "Older adults, plant-based eaters, and people in calorie deficits may benefit, whereas neurological disease applications remain investigational." },[0][1][2]
    { q: "What percentage range of strength improvement is described in the lesson as a typical evidence-based estimate?", type: "type", accepted: ["5-15%", "5–15%", "5 to 15 percent"], explain: "The lesson describes approximate strength improvements in the 5–15% range, though individual results vary." }
  ],
  "6.3": [
    { q: "What is the main practical difference between a creatine loading protocol and a steady low-dose protocol?", options: ["Loading reaches muscle saturation sooner, while steady dosing reaches a similar endpoint more gradually", "Loading uses a different form of creatine", "Steady dosing works only for endurance athletes", "Loading permanently increases the final effect"], correct: 0, explain: "Loading accelerates saturation but is not required for creatine to work and does not necessarily create a greater eventual benefit." },
    { q: "True or false: Once muscle creatine stores are saturated, taking substantially more than the maintenance dose necessarily produces greater performance benefits.", type: "truefalse", correct: false, explain: "After saturation, additional creatine generally offers little extra benefit and may simply be excreted." },
    { q: "Which practices are consistent with the lesson's practical creatine protocol?", type: "multi", options: ["Using creatine monohydrate", "Taking roughly 3–5 g daily for most people", "Taking it with a meal if convenient", "Cycling it because the muscles stop responding permanently"], correct:, explain: "Monohydrate, a regular maintenance dose, and convenient meal timing fit the evidence, while cycling is not required." },[0][1][2]
    { q: "Which form of creatine has the largest research base and is generally the least expensive?", type: "type", accepted: ["creatine monohydrate", "monohydrate"], explain: "Creatine monohydrate is the most extensively studied form and is usually the most economical." }
  ],
  "6.4": [
    { q: "Why can creatinine rise after creatine supplementation without proving kidney damage?", options: ["Creatinine is related to creatine metabolism and the reading can change without impaired filtration", "Creatinine is a vitamin", "Healthy kidneys never produce creatinine", "Creatine removes all waste from blood"], correct: 0, explain: "Creatine metabolism can raise creatinine, so the value must be interpreted with appropriate kidney-function measures and clinical context." },
    { q: "True or false: Someone with known kidney disease should seek medical advice before starting creatine.", type: "truefalse", correct: true, explain: "Pre-existing kidney disease warrants individual clinical assessment rather than assuming that healthy-person safety data apply." },
    { q: "Which situations call for extra caution or medical discussion before creatine use?", type: "multi", options: ["Known kidney disease", "Pregnancy or breastfeeding due to limited safety data", "A history of bipolar disorder", "Being a healthy adult with no relevant conditions"], correct:, explain: "The lesson identifies kidney disease, limited pregnancy data, and possible mania risk in bipolar disorder as reasons for caution." },[0][1][2]
    { q: "What common benign effect can account for early scale-weight gain after starting creatine?", type: "type", accepted: ["water retention", "intramuscular water retention", "muscle water retention"], explain: "Creatine can increase water stored within muscle cells, producing early weight gain without fat gain." }
  ],
  "6.5": [
    { q: "Maya wants faster saturation but has no medical contraindication; what does the loading phase change most directly?", options: ["The time needed to saturate muscle creatine stores", "Whether creatine can work at all", "Whether she gains body fat", "The chemical identity of creatine"], correct: 0, explain: "Loading raises daily intake temporarily to saturate muscle stores faster, but it is not required for eventual effectiveness." },
    { q: "True or false: Early scale-weight gain from creatine should automatically be interpreted as fat gain and permanent bulk.", type: "truefalse", correct: false, explain: "Early gain can reflect temporary or ongoing intramuscular water storage rather than fat accumulation." },
    { q: "Which factors should be considered before giving a minor personalised supplement advice?", type: "multi", options: ["Medical history", "The specific performance goal", "Consultation with a qualified clinician or dietitian", "Whether an older sibling uses the same protocol"], correct:, explain: "A minor's health history, goal, and professional guidance matter more than copying another person's supplement routine." },[0][1][2]
    { q: "What is the term for reaching the maximum practical amount of creatine stored in muscle?", type: "type", accepted: ["saturation", "muscle creatine saturation", "creatine saturation"], explain: "Creatine saturation means muscle stores have reached a level where additional loading offers little extra storage benefit." }
  ],
  "6.6": [
    { q: "When is a protein powder most defensible as a practical choice?", options: ["When it helps someone meet protein needs that are difficult to reach with food", "When it is required for muscle growth in everyone", "When it replaces all fruit and vegetables", "When its label hides the protein source"], correct: 0, explain: "Protein powder is primarily a convenient tool for meeting protein targets when whole-food intake is impractical or insufficient." },
    { q: "True or false: A complete protein powder can be useful without being nutritionally equivalent to a varied whole-food diet.", type: "truefalse", correct: true, explain: "Powders can provide quality protein but generally contribute less of the fibre, vitamins, minerals, and food-matrix benefits found in whole foods." },
    { q: "Which features are useful when evaluating a protein-powder label?", type: "multi", options: ["Protein grams per serving", "The named protein source", "Added sugar and ingredient details", "Third-party sport certification where relevant"], correct:, explain: "Protein amount, source, added ingredients, and independent testing can all help assess a powder's suitability and quality." },[0][1][2][3]
    { q: "Which dairy protein is digested more slowly and is often used before sleep?", type: "type", accepted: ["casein", "casein protein"], explain: "Casein forms a slower-digesting protein source and is commonly used when a prolonged amino-acid supply is desired." }
  ],
  "6.7": [
    { q: "Why are BCAAs generally a poor priority for someone who already consumes sufficient complete protein?", options: ["Complete protein already supplies BCAAs along with all essential amino acids", "BCAAs contain no amino acids", "BCAAs permanently block muscle synthesis", "Complete protein cannot be digested"], correct: 0, explain: "Adequate complete protein already provides leucine, isoleucine, valine, and the other amino acids needed for muscle protein synthesis." },
    { q: "True or false: A proprietary blend makes it easier to know the precise dose of every ingredient.", type: "truefalse", correct: false, explain: "Proprietary blends can conceal individual ingredient amounts, making it difficult to judge whether doses are effective or safe." },
    { q: "Which supplement claims or ingredients receive comparatively stronger support in the lesson?", type: "multi", options: ["Caffeine for some performance contexts", "Creatine monohydrate", "Omega-3 in appropriate situations", "Most unlabelled testosterone boosters"], correct:, explain: "Caffeine, creatine, and omega-3 have more substantial evidence than most vague or proprietary testosterone-booster claims." },[0][1][2]
    { q: "Which pre-workout ingredient can cause harmless tingling through paraesthesia?", type: "type", accepted: ["beta-alanine", "beta alanine"], explain: "Beta-alanine can cause paraesthesia, a tingling sensation, and is used to increase muscle carnosine over time." }
  ],
  "6.8": [
    { q: "Why is the so-called anabolic window less restrictive than many supplement advertisements suggest?", options: ["Total daily protein and calories matter more, and pre-workout food contributes to the post-exercise context", "Muscle cannot use protein after training", "Protein is useful only during sleep", "The body stops digesting food after exercise"], correct: 0, explain: "Post-exercise protein is useful, but the relevant opportunity extends beyond 30 minutes and depends on total intake and prior meals." },
    { q: "True or false: Spreading adequate protein across several meals may be more useful for muscle protein synthesis than eating the entire day's protein in one meal.", type: "truefalse", correct: true, explain: "Distributing protein across multiple substantial servings can provide repeated stimulation of muscle protein synthesis." },
    { q: "Which factors can affect whether fasted training is appropriate for an individual?", type: "multi", options: ["Training intensity and duration", "The person's total energy and protein intake", "Individual symptoms and performance", "A universal requirement that everyone train fasted"], correct:, explain: "Fasted training responses vary with the session and person, so it is not a universal requirement or universal benefit." },[0][1][2]
    { q: "What phrase is commonly used for the exaggerated idea that protein must be consumed immediately after training?", type: "type", accepted: ["anabolic window", "the anabolic window"], explain: "The anabolic-window claim refers to the idea that a very short post-workout period determines all muscle-building results." }
  ],
  "6.9": [
    { q: "Which principle best summarises the module's supplement hierarchy?", options: ["Supplements replace training, sleep, and diet", "Foundational habits come first, then evidence-based supplements may add a smaller benefit", "Every supplement should be taken at a high dose", "Marketing popularity is the strongest evidence"], correct: 1, explain: "The module presents supplements as adjuncts after nutrition, training, sleep, and recovery are addressed." },
    { q: "True or false: Creatine loading is optional because a lower daily dose can eventually saturate muscle stores.", type: "truefalse", correct: true, explain: "Loading speeds saturation but is not necessary for a steady daily dose to work." },
    { q: "Which statements accurately reflect the module?", type: "multi", options: ["Protein powders are convenient rather than mandatory", "Caffeine can improve performance at appropriate doses but may disrupt sleep", "Known kidney disease warrants caution with creatine", "BCAAs are superior to complete protein"], correct:, explain: "The module supports convenience powders, appropriately dosed caffeine, and caution with kidney disease while rejecting BCAA superiority." },[0][1][2]
    { q: "What energy system is most directly supported by creatine during brief maximal efforts?", type: "type", accepted: ["ATP-PCr", "ATP PCr", "phosphagen system", "phosphocreatine system"], explain: "Creatine supports the ATP-phosphocreatine or phosphagen system used for short, high-intensity efforts." }
  ],
  "7.1": [
    { q: "Which practice best reflects naturopathic nutrition's food-as-medicine perspective?", options: ["Considering food quality, preparation, and the person's wider context", "Reducing every food to its calorie number only", "Applying one identical menu to everyone", "Ignoring traditional food practices entirely"], correct: 0, explain: "The naturopathic lens considers whole foods, preparation, individual variation, and food's role in broader health." },
    { q: "True or false: The naturopathic approach treats isolated nutrients and whole foods as automatically identical in effect.", type: "truefalse", correct: false, explain: "It emphasises the food matrix, co-factors, and synergy, suggesting that whole foods may behave differently from isolated nutrients." },
    { q: "Which examples fit the lesson's naturopathic framework?", type: "multi", options: ["Fermentation as a way to alter food properties", "Prebiotic fibre feeding gut microbes", "Bio-individuality", "Assuming one supplement protocol works for everyone"], correct:, explain: "Fermentation, prebiotics, and individualisation are central ideas, whereas one-size-fits-all protocols conflict with bio-individuality." },[0][1][2]
    { q: "What term describes the belief that food can support health beyond simply supplying calories?", type: "type", accepted: ["food as medicine", "food-as-medicine"], explain: "Food-as-medicine describes the view that food can influence health through nutrients, bioactive compounds, and dietary patterns." }
  ],
  "7.2": [
    { q: "Why can eating fibre affect the gut microbiome even though human digestive enzymes do not fully break down some fibres?", options: ["Gut microbes can ferment fibre and produce short-chain fatty acids", "Fibre is converted directly into muscle", "Fibre sterilises the colon", "Human enzymes convert all fibre into cholesterol"], correct: 0, explain: "Microbes in the colon ferment otherwise indigestible fibre into metabolites such as acetate, propionate, and butyrate." },
    { q: "True or false: Probiotic effects are often strain-specific, so a product that helps one condition is not guaranteed to help every person or symptom.", type: "truefalse", correct: true, explain: "Evidence for probiotics depends on the strain, dose, condition, and person rather than applying uniformly to all products." },
    { q: "Which functions are associated with the gut microbiome?", type: "multi", options: ["Fibre fermentation", "Interaction with immune function", "Influence on gut-barrier integrity", "Guaranteed prevention of every chronic disease"], correct:, explain: "The microbiome contributes to fermentation, immune regulation, and barrier function, but it cannot guarantee prevention of all disease." },[0][1][2]
    { q: "What are the short-chain fatty acids acetate, propionate, and butyrate produced from in the colon?", type: "type", accepted: ["fermented fibre", "dietary fibre", "fibre"], explain: "Gut bacteria ferment dietary fibre into short-chain fatty acids, including acetate, propionate, and butyrate." }
  ],
  "7.3": [
    { q: "Why is an elimination-and-rechallenge process more informative than simply removing many foods indefinitely?", options: ["Reintroduction tests whether symptoms reliably return with a specific food", "Permanent restriction proves every removed food was harmful", "It eliminates the need to consider nutrition adequacy", "It measures IgE antibodies directly"], correct: 0, explain: "Systematic reintroduction helps identify whether a suspected food is actually associated with symptoms while avoiding unnecessary long-term restriction." },
    { q: "True or false: IgG food panels are universally accepted as the definitive diagnostic test for food sensitivity.", type: "truefalse", correct: false, explain: "IgG findings can reflect exposure or tolerance and are not universally validated as definitive food-sensitivity diagnoses." },
    { q: "Which distinctions are accurate?", type: "multi", options: ["IgE allergy can be immediate and potentially severe", "Lactose intolerance is usually non-immune", "Elimination followed by reintroduction can help investigate suspected intolerance", "Every delayed symptom after eating proves an IgG-mediated sensitivity"], correct:, explain: "Allergy, intolerance, and sensitivity have different mechanisms, and delayed symptoms alone do not prove a specific immune pathway." },[0][1][2]
    { q: "What does FODMAP refer to in the context of food sensitivity diets?", type: "type", accepted: ["fermentable short-chain carbohydrates", "fermentable oligosaccharides disaccharides monosaccharides and polyols", "fermentable carbohydrates"], explain: "FODMAPs are fermentable short-chain carbohydrates that can trigger gastrointestinal symptoms in some sensitive people." }
  ],
  "7.4": [
    { q: "What distinguishes an adaptogen from a conventional stimulant in the lesson's framework?", options: ["An adaptogen is intended to support stress adaptation and regulation rather than provide an immediate stimulant effect", "An adaptogen always causes an instant energy surge", "A stimulant cannot affect alertness", "Adaptogens are purified vitamins"], correct: 0, explain: "Adaptogens are described as supporting adaptation and homeostasis, whereas stimulants typically produce more immediate activation." },
    { q: "True or false: Traditional use of an herb is enough by itself to establish that it is safe and effective for every modern indication.", type: "truefalse", correct: false, explain: "Traditional use can inform hypotheses, but safety, dose, interactions, and clinical evidence still require evaluation." },
    { q: "Which cautions are relevant to the herbs discussed?", type: "multi", options: ["Ashwagandha may be unsuitable in some thyroid conditions", "Rhodiola may be stimulating for some people", "Ginseng may affect blood sugar or blood pressure", "Pregnancy automatically makes every herb proven safe"], correct:, explain: "The lesson highlights possible thyroid, stimulation, blood-sugar, and blood-pressure concerns, while pregnancy generally calls for caution due to limited data." },[0][1][2]
    { q: "Which adaptogen is most associated in the lesson with stress and cortisol reduction?", type: "type", accepted: ["ashwagandha", "Withania somnifera"], explain: "Ashwagandha is the adaptogen highlighted for potential stress and cortisol-related benefits." }
  ],
  "7.5": [
    { q: "Why might fasting increase the risk of harm for someone with a history of disordered eating?", options: ["Rigid food restriction can reinforce problematic eating patterns", "Fasting guarantees adequate nutrition", "Disordered eating improves with every form of restriction", "Fasting eliminates psychological stress"], correct: 0, explain: "Fasting can intensify restrictive or compulsive patterns, so the potential risks may outweigh benefits for people with eating-disorder histories." },
    { q: "True or false: Intermittent fasting is a meal-timing pattern rather than a guarantee of superior weight loss regardless of total intake.", type: "truefalse", correct: true, explain: "Fasting may help some people reduce intake, but outcomes still depend on overall energy intake, diet quality, adherence, and individual response." },
    { q: "Which people should generally avoid unsupervised fasting?", type: "multi", options: ["Pregnant people", "Underweight individuals", "People with a history of disordered eating", "All healthy adults regardless of circumstances"], correct:, explain: "Pregnancy, underweight status, and eating-disorder history are important contraindications or caution flags for unsupervised fasting." },[0][1][2]
    { q: "In a 16:8 fasting pattern, how many hours is the eating window?", type: "type", accepted: ["8 hours", "eight hours"], explain: "The 16:8 pattern usually means 16 hours without eating followed by an 8-hour eating window." }
  ],
  "7.6": [
    { q: "Why is 'organic' not a complete synonym for 'nutritionally superior'?", options: ["Nutrient differences are often modest and depend on the food, farming system, and overall diet", "Organic foods contain no nutrients", "Organic certification measures only calorie content", "Conventional foods are always more nutritious"], correct: 0, explain: "Organic production can reduce some pesticide exposures, but nutritional differences vary and do not make the label a complete measure of diet quality." },
    { q: "True or false: Frozen or canned produce can still be nutritionally useful when fresh produce is expensive or unavailable.", type: "truefalse", correct: true, explain: "Frozen and appropriately canned foods can retain substantial nutrients and improve affordability and access." },
    { q: "Which factors are part of the lesson's broader definition of food quality?", type: "multi", options: ["Degree of processing", "Farming and pesticide practices", "Preparation and storage", "The front-of-pack health claim alone"], correct:, explain: "Food quality includes production, processing, preparation, and storage, not merely a marketing claim on the label." },[0][1][2]
    { q: "What food-quality characteristic refers to the amount of useful nutrients relative to the energy provided?", type: "type", accepted: ["nutrient density", "nutrient-dense"], explain: "Nutrient density describes how many beneficial nutrients a food provides for its calorie content." }
  ],
  "7.7": [
    { q: "Which approach best represents a critical use of naturopathic ideas?", options: ["Use whole-food and lifestyle strategies while checking claims against evidence and individual safety", "Accept every traditional claim without testing", "Reject all conventional research", "Prescribe the same protocol to every person"], correct: 0, explain: "The course presents naturopathic concepts as potentially useful when integrated critically with evidence, context, and safety considerations." },
    { q: "True or false: The module supports treating 'natural' as automatically safe.", type: "truefalse", correct: false, explain: "Herbs and concentrated natural products can have pharmacological effects, interactions, and contraindications." },
    { q: "Which statements summarise major themes of the module?", type: "multi", options: ["Gut health involves the microbiome and barrier function", "Elimination diets should include systematic reintroduction", "Adaptogens are adjuncts rather than replacements for foundational habits", "One diet or supplement works identically for everyone"], correct:, explain: "The module covers microbiome function, structured elimination and reintroduction, and cautious adjunctive use of adaptogens while rejecting one-size-fits-all claims." },[0][1][2]
    { q: "What principle describes tailoring nutrition to a person's symptoms, context, and response rather than applying one universal plan?", type: "type", accepted: ["bio-individuality", "bio individuality", "individualisation", "individualization"], explain: "Bio-individuality or individualisation means adapting nutrition to the person's distinct needs and responses." }
  ],
  "8.1": [
    { q: "A study finds that people who eat more of a food have lower disease rates, but participants chose their own diets; what is the key limitation?", options: ["Confounding and selection effects can make association look causal", "Randomisation is guaranteed", "The result proves the food prevents disease", "Observational data cannot contain any useful information"], correct: 0, explain: "Self-selected observational data can reveal associations but may be distorted by differences between people who do and do not eat the food." },
    { q: "True or false: A surrogate marker such as LDL cholesterol is always equivalent to a demonstrated reduction in illness or death.", type: "truefalse", correct: false, explain: "Surrogate changes may be informative but do not always translate into improved clinical outcomes." },
    { q: "Which are sensible ways to critically evaluate a nutrition study?", type: "multi", options: ["Check sample size and study duration", "Distinguish randomised trials from observational studies", "Look for conflicts of interest", "Assume animal findings automatically apply to humans"], correct:, explain: "Sample size, duration, design, and funding affect interpretation, while animal findings require human confirmation." },[0][1][2]
    { q: "What is the term for a variable that distorts the apparent relationship between an exposure and an outcome?", type: "type", accepted: ["confounder", "confounding variable", "confounding"], explain: "A confounder is related to both the exposure and outcome and can create or distort an apparent association." }
  ],
  "8.2": [
    { q: "Why is the claim that all calories affect the body identically an oversimplification?", options: ["Food composition affects satiety, thermic effect, nutrient density, and metabolic responses", "Calories are not a unit of energy", "Only vitamins contain energy", "Energy balance never matters"], correct: 0, explain: "Calories measure energy, but protein, fibre, processing, and food composition influence how that energy is processed and experienced." },
    { q: "True or false: A food described as 'natural' is automatically safe, effective, and appropriate for every person.", type: "truefalse", correct: false, explain: "Natural products can be ineffective, contaminated, interactive with medicines, or unsuitable for particular conditions." },
    { q: "Which claims should be treated sceptically?", type: "multi", options: ["A detox tea removes all toxins", "An alkaline diet can cure cancer", "One food is universally inflammatory for everyone", "A varied diet can support health"], correct:, explain: "Absolute detox, cure, and universal-food claims overstate evidence, whereas varied dietary patterns can reasonably support health." },[0][1][2]
    { q: "What is the fallacy of treating a correlation as proof that one factor caused another called?", type: "type", accepted: ["confusing correlation with causation", "correlation-causation fallacy", "correlation does not imply causation"], explain: "Correlation shows that variables move together but does not by itself establish a causal mechanism." }
  ],
  "8.3": [
    { q: "Which meal-preparation strategy best supports consistency without requiring a different recipe every day?", options: ["Prepare versatile ingredients and combine them using simple meal templates", "Cook only elaborate meals from scratch at every sitting", "Skip preparation and rely on hunger alone", "Remove all social meals permanently"], correct: 0, explain: "Preparing flexible staples and using repeatable templates reduces effort while preserving variety and adherence." },
    { q: "True or false: A sustainable nutrition routine can include enjoyable social meals without requiring perfection at every meal.", type: "truefalse", correct: true, explain: "The course emphasises consistency and flexible habits, including an 80:20 approach, rather than all-or-nothing perfection." },
    { q: "Which practices support mindful eating?", type: "multi", options: ["Eating with fewer distractions", "Checking whether hunger or emotion is driving eating", "Pausing before reaching complete fullness", "Labelling foods morally as good or bad"], correct:, explain: "Mindful eating involves attention, hunger and fullness awareness, and reducing moral judgement rather than using guilt-based labels." },[0][1][2]
    { q: "What percentage-based rule in the lesson represents eating well most of the time while allowing flexibility?", type: "type", accepted: ["80/20", "80 20", "80:20", "eighty twenty"], explain: "The 80:20 approach encourages generally healthful eating while leaving room for enjoyment and social flexibility." }
  ],
  "8.4": [
    { q: "What is the first useful step when designing a personal nutrition framework?", options: ["Audit current eating patterns, goals, constraints, and symptoms", "Copy the most popular online diet", "Remove every food immediately", "Choose supplements before examining diet"], correct: 0, explain: "A personal framework should begin with understanding current habits, objectives, practical constraints, and relevant health considerations." },
    { q: "True or false: A personal nutrition plan should be adjusted when results, preferences, or circumstances show that the original plan is not working.", type: "truefalse", correct: true, explain: "Personalisation is iterative: monitoring outcomes and barriers allows the plan to be refined rather than followed rigidly." },
    { q: "Which elements belong in a realistic personal nutrition framework?", type: "multi", options: ["A clearly defined goal", "Foods and routines that fit the person's budget and schedule", "A way to monitor outcomes", "Rigid rules that ignore medical advice and social context"], correct:, explain: "Effective frameworks connect goals with feasible habits and feedback, while rigid rules that ignore context are less sustainable and safe." },[0][1][2]
    { q: "What principle means that a nutrition plan should be adapted to a person's individual needs and responses?", type: "type", accepted: ["bio-individuality", "bio individuality", "individualisation", "individualization"], explain: "Bio-individuality means that a useful nutrition plan accounts for differences in needs, preferences, health, and response." }
  ],
  "8.5": [
    { q: "Which sequence best reflects the course's overall approach to nutrition decisions?", options: ["Assess goals and context, prioritise foundational habits, evaluate evidence, then consider targeted additions", "Start with the most expensive supplement, then change diet if needed", "Follow population guidelines rigidly without individual adjustment", "Choose claims based on certainty of marketing language"], correct: 0, explain: "The course combines individual context, foundational nutrition, critical evidence appraisal, and selective use of supplements or specialised approaches." },
    { q: "True or false: A strong nutrition framework can acknowledge uncertainty instead of treating every nutrition claim as absolutely true or false.", type: "truefalse", correct: true, explain: "Nutrition evidence varies in quality and context, so calibrated conclusions are more appropriate than blanket certainty." },
    { q: "Which principles are consistent with the whole course?", type: "multi", options: ["Food quality matters alongside energy intake", "Protein needs vary with goals and life stage", "Supplements should be targeted rather than assumed necessary", "A single diet is guaranteed to suit everyone"], correct:, explain: "The course repeatedly combines energy and quality, individualises protein needs, and treats supplements as targeted tools rather than universal requirements." },[0][1][2]
    { q: "What is the broad term for the body's use of food components to support energy, structure, and physiological function?", type: "type", accepted: ["nutrition"], explain: "Nutrition encompasses the intake and use of food components for energy, tissue building, regulation, and health." }
};
